### ISSUE TITLE
Add information of different sharing settings

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#104]
https://github.com/Sage-Bionetworks/synapseDocs/blob/master/articles/access_controls.md

is missing information about what edit, edit+delete, view and administrator means.

**Comment by larssono** [comment]
Also, the section starting:"Local Sharing settings are illustrated in the diagram below. " makes me think of a GRE logic question.

**Comment by MegDoerr** [comment]
The definition of the various roles has never been part of the Content Controls section of the tutorial. Would you like it to become part of this section now?

If you can think of a way to more clearly represent inheritance of content controls, please share. Christine and I have reviewed several times to no apparent impact.

**Comment by larssono** [comment]
Also see: #188

**Comment by meredithslota** [comment]
Agreed -- we need a separate article on with the different "rights" do and how project vs. local settings interact. I will take this one.

**Comment by meredithslota** [comment]
See https://github.com/Sage-Bionetworks/synapseDocs/pull/332
