### ISSUE TITLE
Update references to Synapse Objects

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#116]
We mix the use of file and File, table and Table etc.  We should consistently use uppercase and surround them with code blocks e.g. `File  `when referring to Synapse Objecs.

**Comment by larssono** [comment]
Has been updated but need to fix external storage locations and new articles (pull request from Tom on downloads PR#140)

**Comment by kdaily** [comment]
@ychae did all the work everywhere everything.
