### ISSUE TITLE
Download data from synapse tutorial

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/synapseDocs#140]
It should include: (all clients):
- downloadLocation (To download the file to specific location)
- downloadFile = T/F (To just get metadata about the entity)
- version (Get specific version of synapse entity)
- ifcollision = (Determines how to handle file collisions. May be "overwrite.local", "keep.local", or "keep.both". Defaults to "keep.both".)

Commandline client only
- `-r` (Recursively gets everything in a folder and builds the folder structure)
- `-q` (Downloads all the files that is returned from a synapse query)
- limitSearch (Synapse ID of a container such as project or folder to limit search for files if using a path.)

Python client only
- followLink = defaults to False (If the entity is a link, follow the link and download the actual file)
- limitSearch (Synapse ID of a container such as project or folder to limit search for files if using a path.)

R client only
- load (If TRUE then deserialize the downloaded file into memory, using the R 'load' command (See getObject, listObjects)

**Comment by thomasyu888** [comment]
First pass here:  https://github.com/thomasyu888/synapseDocs/commit/cdd0018470e8ecdcf452aab63800f6821833634b 

Feel feel to comment.

**Comment by meredithslota** [comment]
@thomasyu888 This seems done, do you know if there is remaining work?

**Comment by kdaily** [comment]
@ychae fixed it!

http://docs.synapse.org/articles/downloading_data.html
