### ISSUE TITLE
How to log into Synapse and store credentials

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#151]
Need info on setting up `.synapseConfig`. Brought up in Help forum (https://www.synapse.org/#!Synapse:syn5637528/discussion/threadId=631) - refer to old docs at https://www.synapse.org/#!Synapse:syn2375225/wiki/62763.

Add to Getting Started Guide, and somewhere in an existing User Guide?

**Comment by larssono** [comment]
duplicate of #175
