### ISSUE TITLE
Move table examples

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#154]
The File:
http://hud.rel.rest.doc.sagebase.org.s3-website-us-east-1.amazonaws.com/org/sagebionetworks/repo/web/controller/TableExamples.html

should be represented in the doc site.

- [x] Make sure file is part of rest docs
- [x] Update help link in /articles/tables.html to point to this page.
- [x] Update link in rest docs to point to the file as it lives in docs.

**Comment by ychae** [comment]
currently located at: http://docs.synapse.org/rest/org/sagebionetworks/repo/web/controller/TableExamples.html
