### ISSUE TITLE
migrate and update content from Challenge submission

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#157]
Please migrate this page to the docs site:
https://www.synapse.org/#!Synapse:syn1768504/wiki/56101
Note:  The page is out of date and needs to be updated, e.g. there is no longer a joinEvaluation() method and the team param of submit() is 'team' not 'teamName'.  More detail here: https://sagebionetworks.jira.com/browse/SYNPY-385

**Comment by meredithslota** [comment]
https://sagebionetworks.jira.com/browse/SYNPY-385 is marked closed, so closing this one as well.
