### ISSUE TITLE
Update links in Synapse to new doc site.

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#17]
The following wiki's (and other locations) should be edited to redirect to content in docs.synapse.org before going live.
- [x] https://www.synapse.org/#!Synapse:syn3722562/wiki/393364 (Standalone Wikis - Synapse Forms) -> needs to be added to wiki help and see if can redirect. Ask Jay.
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56101 (Getting Started with the Python client - Submitting a file to an evaluation or a challenge)
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/55491 (Getting Started with the R client - Access content)
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/57112 (Getting Started with the R client - Submitting a file to and Evaluation or Challenge)
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56095 (Getting Started with the Python client - Accessing Synapse-stored content)
- [x]   https://www.synapse.org/#!Synapse:syn2305384/wiki/61140  -> /articles/accounts_certified_users_and_qualified_researchers.html
- [x] https://www.synapse.org/#!Synapse:syn2305384/wiki/63529 -> /articles/access_controls.html
- [x] https://www.synapse.org/#!Synapse:syn2305384/wiki/62866 -> articles/faq.html
- [x] https://www.synapse.org/#!Wiki:syn2305384/ENTITY/65146 -> articles/audits.html
- [x] https://www.synapse.org/#!ProjectsHome:0 -> articles/making_a_project.html
- [x] rest.syanpse.org -> /rest/
- [x] certification quiz links -> update
- [x] http://python-docs.synapse.org/ -> http://docs.synapse.org/python/
- [x]  https://www.synapse.org/#!Synapse:syn3316305/wiki/ -> articles/custom_storage_location.md
- [x] https://sagebionetworks.jira.com/wiki/display/PLFM/Repository+Service+API#RepositoryServiceAPI-QueryAPI -> articles/annotation_and_query.html
- [x]  r-docs.synapse.org -> docs.synapse.org/r
- [x] https://www.synapse.org/#!Help:Governance -> articles/governance.html
- [x] https://www.synapse.org/#!Synapse:syn2305384/wiki/65146 -> articles/governance.html
- [x]  https://www.synapse.org/#!Synapse:syn2305384/wiki/63409 -> articles/contribute_and_access_controlled_use_data.html
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56099 -> /articles/provenance.html
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/55486 -> /articles/provenance.html
- [x] https://www.synapse.org/#!Wiki:syn3722562/ENTITY/292631 -> /assets/other/notarized_letter_template
- [x] https://www.synapse.org/#!Wiki:syn3722562/ENTITY/292619 -> /assets/other/signing_official_template
- [x] https://www.synapse.org/#!Synapse:syn3722562/wiki/390754 -> /assets/other/oath.html
- [x] https://www.synapse.org/#!Synapse:syn2305384/wiki/61139  -> multiple articles.
- [x]  https://www.synapse.org/#!Synapse:syn2305384/wiki/248044 -> docs.synapse.org
- [x] https://www.synapse.org/#!Synapse:syn1661878/wiki/27472 -> /articles/provenance.html
- [x] link in controlled used pop-up  -> http://docs.synapse.org/articles/governance.html
- [x] links from code examples at bottom of entity page -> http://docs.synapse.org/articles/getting_started.html
- [x] https://www.synapse.org/#!Synapse:syn1669771/wiki/27425 -> docs.synapse.org
- [x] https://www.synapse.org/#!Synapse:syn1669771/wiki/54546 -> docs.synapse.org/articles/getting_started.html
- [x] https://www.synapse.org/#!Synapse:syn1669771/wiki/54547 -> /articles/making_a_project.html
- [x] https://www.synapse.org/#!Synapse:syn1669771/wiki/54708 -> /articles/getting_started.html
- [x] https://www.synapse.org/#!Synapse:syn3722562/wiki/219292 -> /articles/accounts_certified_users..
- [x] https://www.synapse.org/#!Synapse:syn3722562/wiki/235721 (Standalone Wikis - Genome Browser) should perhaps be merged into wiki widget for genome browser.
- [x] https://www.synapse.org/#!Synapse:syn3722562/wiki/390320 (Standalone Wikis - Synapse Java Client) Move to getting started- Jay?
- [x] https://www.synapse.org/#!Synapse:syn3722562/wiki/266764 (Standalone Wikis - Validation) -> /articles/accounts_certified... if it can be moved ask Jay.
- [x] https://www.synapse.org/#!Synapse:syn3722562/wiki/338504 (Standalone Wikis - Why get validated)
- [x] https://www.synapse.org/#!Synapse:syn2305384/wiki/63259 ->/articles/getting_started.html
- [x] https://www.synapse.org/#!Synapse:syn2305384/wiki/248044 -> docs.synapse.org
- [x] https://www.synapse.org/#!Synapse:syn2305384/wiki/64455 -> /articles/accounts_certified...
- [x] https://www.synapse.org/#!Synapse:syn2375225/wiki/62763 -> getting_started.html
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/54750 -> getting_started.html
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56068 -> getting_started.html
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56098 -> getting_started.hmtl
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56099 (Getting Started with the Python client - Building up provenance relationships)
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56100 -> annotations_query.html
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56102 -> tables.html
- [x] https://www.synapse.org/#!Synapse:syn1768504/wiki/56103 -> wikis.html
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/55157 (Getting Started with the R client)
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/56017 (Getting Started with the R client - Installation and logging in)
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/55490 (Getting Started with the R client - Creating new Synapse content)
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/55486 (Getting Started with the R client - Building provenance relationships)
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/55485 (Getting Started with the R client - Querying Synapse)
- [x] https://www.synapse.org/#!Synapse:syn1834618/wiki/75036 (Getting Started with the R client - Synapse Tables)
- [x] https://www.synapse.org/#!Synapse:syn1901847/wiki/56044 -> docs.synapse.org

**Comment by meredithslota** [comment]
@kdaily Will create issues for each of the five remaining tasks as they are each rather large, close this one out, and we'll follow up with each remaining task individually.

**Comment by meredithslota** [comment]
Remaining items addressed; the content was already in the docs site so no pull requests, just updating old wikis pages with links to docs site. :)
