### ISSUE TITLE
config article

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseDocs#175]
Article on the various components that can be placed in a .synapseConfig file

**Comment by larssono** [comment]
From duplicat issue:
Need info on setting up .synapseConfig. Brought up in Help forum (https://www.synapse.org/#!Synapse:syn5637528/discussion/threadId=631) - refer to old docs at https://www.synapse.org/#!Synapse:syn2375225/wiki/62763.

Add to Getting Started Guide, and somewhere in an existing User Guide?

**Comment by kdaily** [comment]
@kimyen can you add the link to Confluence?

**Comment by kimyen** [comment]
Here is the link: https://sagebionetworks.jira.com/wiki/spaces/SYNR/pages/285638657/Synapse+Issue+Validation

**Comment by meredithslota** [comment]
@ychae Will help write the article including references to the self-documenting clients, and I will follow up with users and ensure older documentation is cleared out.

**Comment by ychae** [comment]
@kdaily @meredithslota Should I add in a line to this article to let users know that a commented out `.synapseConfig` file with all the possible parameters gets created in your home directory when you run `python setup.py install` of the Synapse python client?

**Comment by kdaily** [comment]
Oooh! Yes!

**Comment by ychae** [comment]
See PR #344 for the added bit about an automatically created config file.

**Comment by kdaily** [comment]
closed by #344 #200 #341
