### ISSUE TITLE
Wiki text table documentation insufficient

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseDocs#181]
The wiki page should be updated to clearly describe how to create a text table. I think it's at the bottom of the page, but should be moved up and clarified with a text description.

**Comment by ychae** [comment]
Change "Tip" to something like "To insert large amounts of text, use the widget "Table: Paste tabular data""

**Comment by sgosline** [comment]
I would leave the original tip and then add the paste option as well (I could never get the paste option to work? Maybe because my data was space-delimited instead of tab?).

**Comment by larssono** [comment]
Maybe the existing tip just needs to be rephrased but as it was written I wasn't able to understand what the existing tip even means.  What was it referring to?  Maybe with some more contextual information about how to create tables it makes sense. 

In general having the example wasn't enough to know how to create tables.

**Comment by ychae** [comment]
Would this format help to clarify tables in wikis?

![wiki_tables](https://cloud.githubusercontent.com/assets/12868382/21652434/7929019a-d261-11e6-8061-80fcecd13465.png)

**Comment by larssono** [comment]
I don’t think it is necessary to show an example how it will look.  I would just add some more text above the table markdown.

To create a table you separate the columns by the pipe character (|).  A Header can be added by separating the first row by dashes (-).  A header allows the table to be sorted by each column.  A simple table would be created by the following markdown.

For more table settings see the formatting guide at the top of the wiki editor.
