### ISSUE TITLE
More detail needed in description of Synapse sharing levels

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseDocs#188]
There are multiple sharing levels in Synapse that are not documented on http://docs.synapse.org/articles/access_controls.html. 

e.g. what does 'Moderate' mean? What can an administrator do that someone with edit/delete cannot?

**Comment by kdaily** [comment]
http://docs.synapse.org/articles/discussion.html#moderating-a-discussion-forum

**Comment by larssono** [comment]
Dupliccate of #104
