### ISSUE TITLE
Document how to keep Synapse email from going to gmail spam folder

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#189]
Some comments here: 
https://sagebionetworks.jira.com/browse/PLFM-3462
for example, Kenny says:
I match
'from:(*@synapse.org)'
and mark automatically as not spam as a filter.

**Comment by kdaily** [comment]
https://www.synapse.org/#!SynapseForum:threadId=1138

**Comment by larssono** [comment]
This is currently a pinned topic in the discussion forum.
