### ISSUE TITLE
update Python docs to 1.6.1

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#192]
Python docs still are at 1.5.1, but 1.6.1 was released.

**Comment by larssono** [comment]
I am not seeing that see 
http://docs.synapse.org/python/
The old python-docs.synapse.org is being changed to a redirect bu Xa.   Please close if this is satisfactory. 
--
Please excuse any fat fingers - sent from my phone. Friday, 04 November 2016, 01:00PM -07:00 from Kenneth Daily  notifications@github.com :

**Comment by kdaily** [comment]
My bad - when I type python docs in my search bar, the history goes to the old one.
