### ISSUE TITLE
Format problem on docs for certified users page

### ISSUE THREAD

**Issue by xschildw** [Sage-Bionetworks/synapseDocs#194]
See  http://docs.synapse.org/articles/accounts_certified_users_and_qualified_researchers.html.

![docs1](https://cloud.githubusercontent.com/assets/1766159/20360499/ced45c56-abe8-11e6-8f43-c43c0d90889c.png)
![docs2](https://cloud.githubusercontent.com/assets/1766159/20360500/cedaceec-abe8-11e6-9485-d08c8f2d6a54.png)

**Comment by ychae** [comment]
@xschildw Could you list the steps that got you to this page? I'm attempting to track down all the broken links.

**Comment by xschildw** [comment]
Got there by clicking on 'Become a certified user' panel on the Synapse home page.
From talking to Larsson, we go to an old link 'http://docs.synapse.org/articles/accounts_certified_users_and_qualified_researchers.html'
when we should be going to
'http://docs.synapse.org/articles/accounts_certified_users_and_profile_validation.html'.
Opened SWC-3391 to fix the link in portal.

**Comment by ychae** [comment]
Added a redirect so if anyone lands on the old page they will be automatically redirected to the correct one (#199).
