### ISSUE TITLE
more docs on dates in tables

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#201]
Had a user post in help forum (https://www.synapse.org/#!SynapseForum:threadId=1276) that got strange number representation of date from a table (which is because they're stored as timestamps). Providing some more info about what kind of timestamp we store and possibly some Python/R code examples would be useful.

**Comment by meredithslota** [comment]
I will add this to the Tables docs update that I plan to do after additional SQL functionality is released, since that will help with this issue as well.

**Comment by kdaily** [comment]
Update some here with new content or links to relevant info:

http://docs.synapse.org/articles/tables.html#using-tables

**Comment by meredithslota** [comment]
@kimyen will extend the vignette on tables to include date/time from timestamp stuff.

**Comment by kimyen** [comment]
@nickgros has done this in the scope of working on datetime conversion in synapser. His change will be in synapser 0.5.

**Comment by meredithslota** [comment]
I'm closing this because the relevant changes will be released shortly as part of synapser-0.5.
