### ISSUE TITLE
R docs updates being pushed to r-docs.synapse.org

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseDocs#218]
Follow Jira here: https://sagebionetworks.jira.com/browse/SYNR-1073

The latest r docs have been copied over to docs.synapse.org/r. Xa is currently updating the code to have Jenkins push to the current docs site (see Jira).

**Comment by larssono** [comment]
@ychae  please check if this is done and close.

**Comment by ychae** [comment]
@meredithslota Xa is manually updating the docs site for every update. So the R docs are staying up to date, but not automatically. Should we close this?

**Comment by kdaily** [comment]
Approach changed. Talk to @kimyen for info, closing.
