### ISSUE TITLE
more docs on security features

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#224]
Requested from external collabs (and from their higher-ups) regarding security of data.

**Comment by meredithslota** [comment]
What does this mean, @kdaily? I'm happy to help write this, but would love more detail offline about what the concerns are specifically.

**Comment by meredithslota** [comment]
Closing this for now, but as security policies are developed and formalized as part of audit, we'll publish what we can to the docs site.
