### ISSUE TITLE
Add model use case with instructions for using cytoscape plug-in

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synapseDocs#23]
Need both 'how do i work with model data' and 'how do i use the cytoscape plug-in'

**Comment by meredithslota** [comment]
@kkdang I am happy to write this article if you can point me to someone who knows how to use this widget and can provide me with sample files for the tutorial. Do you know who this might be?

**Comment by kkdang** [comment]
Sorry for the late reply, unfortunately, I do not know how to use it nor have sample files.

**Comment by meredithslota** [comment]
There's no "Won't Fix" in GitHub issues, but because this isn't a widely used feature nor can we find someone who actually knows the best way to use it, let's not invest effort here. Closing.
