### ISSUE TITLE
synapseutils link broken in python docs

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#230]
The link to synapseutils in page: http://docs.synapse.org/python/ is broken

**Comment by ychae** [comment]
This repo doesn't exist anymore, I believe most of the functionality has been merged into the clients themselves. Should I still point to certain functionalities?

**Comment by ychae** [comment]
https://github.com/Sage-Bionetworks/synapsePythonClient/tree/develop/synapseutils

**Comment by larssono** [comment]
It looks like the docs for the synapseutils package are not being generated when generating from source in the Python client.  I have created [SYNPY-471](https://sagebionetworks.jira.com/browse/SYNPY-471)
