### ISSUE TITLE
update Python doc's around changing file name

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#232]
With the implementation of PLFM-4108, the mechanism for file name override has changed, so we need to update in the Python doc's how to change a file name.

**Comment by xschildw** [comment]
That's in 'http://docs.synapse.org/python/Entity.html#synapseclient.entity.File'.

**Comment by ychae** [comment]
new convenience function here: https://github.com/Sage-Bionetworks/synapsePythonClient/blob/develop/synapseutils/copy.py

**Comment by wildaces215** [comment]
Is this still open I would like to tackle it!

**Comment by larssono** [comment]
Actually, this was resolved in the release of the [1.6.2](https://github.com/Sage-Bionetworks/synapsePythonClient/releases/tag/v1.6.2) release of the synapsePythonClient
