### ISSUE TITLE
Can't access Synapse wiki today

### ISSUE THREAD

**Issue by adurbin2** [Sage-Bionetworks/synapseDocs#233]
Apologies if this message is posted in the wrong area... We've not been able to access our Synapse wiki all morning. 

Error message reads:

This site can't be reached
www.synapse.org's server DNS address could not be found
Try running Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

Thanks for any information.
adurbin@ucsc.edu

**Comment by kdaily** [comment]
Hello! Not seeing anything on our end (I also tried this: http://www.isup.me/synapse.org).

Can you try a different web browser? This error seems relatively common on Google Chrome.

I would suggest waiting a while or reaching out to a local network admin.

**Comment by adurbin2** [comment]
Hi, thanks for such a fast response! I just tried using Safari - it says this:

Safari can't find the Server
Safari can't open the page "https://www.synapse.org/#!Synapse ..blablabla... /wiki/398680" because Safari can't find the server "www.synapse.org"

I've checked with two other users who also cannot access it, and I have been trying for 5 hours (since 8am). Very concerned for our wiki.

**Comment by kdaily** [comment]
Can you send your Synapse user name to me at kenneth.daily@sagebase.org? I'm going to move this conversation over to our help forum and loop in our sys admin.

**Comment by kdaily** [comment]
Moved this to our forum at https://www.synapse.org/#!SynapseForum:threadId=1718.
