### ISSUE TITLE
programmatic usage of Wiki widgets

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#237]
always wanted to know how in an RMarkdown file for example to insert a specific widget (e.g. what is the markdown format of the params for a widget, and how do I need to sanitize the text)

**Comment by meredithslota** [comment]
@kdaily For ALL widgets or for specific ones?

**Comment by kdaily** [comment]
Guess I would start with specific high value ones, or easy ones? I often want to specify a user or team, insert a table query.

I would say plotting might be important now too. Will go through the list.

**Comment by meredithslota** [comment]
Overall, this isn't something that we think belongs in the docs site, but we do think that widgets should be somewhat self-documenting (and more helpful than they are now). Assigning to me to file the appropriate JIRA ticket.

**Comment by meredithslota** [comment]
https://sagebionetworks.jira.com/browse/SWC-4039
