### ISSUE TITLE
add info for non-US users about where metadata/annotations/provenance is stored

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#238]
Had a question from a user regarding non-US use (within the EU) that requires specific data to reside within specific geographical areas. Our docs don't make it clear that even with external storage locations, US-based servers are still utilized.

**Comment by meredithslota** [comment]
Goal is to clarify that metadata and data are not necessarily stored co-located.

**Comment by meredithslota** [comment]
Added a note and reorganized some content in https://github.com/Sage-Bionetworks/synapseDocs/pull/333
