### ISSUE TITLE
DOI and citing

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#239]
How do I create a DOI?

If a DOI exists on something in Synapse, how do I cite it in a publication?

**Comment by kdaily** [comment]
To be clear, the second question is open ended and related to a few other existing Jira issues...

**Comment by meredithslota** [comment]
I will write the article re: (a) what is a DOI, (b) what entities in Synapse can have DOIs, (c) how to make DOIs in Synapse, and (d) how to cite/use them. If we need additional info re: how to make/use them, we can do a v2.

**Comment by kdaily** [comment]
https://sagebionetworks.jira.com/browse/SYNPY-588 is open for py-1.8
