### ISSUE TITLE
Add documenation to wikis about using html previews

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#241]

**Comment by larssono** [comment]
Look at Confluence page: How to embed 3rd pawrty HTML in Synapse.

**Comment by ychae** [comment]
Is this something we're making available to the public? I understood it as a feature for a few internal users only.

**Comment by larssono** [comment]
This is public to anyone. But only people on the html group can add html with javascript.

**Comment by meredithslota** [comment]
@larssono I don't think that's true -- I just tested and with my "anon" user (not a part of the HTML group), I cannot create useful HTML previews; any uploaded HTML file previews as plaintext. I'm going to close this since it's not (yet) a docs issue.
