### ISSUE TITLE
how to delete provenance

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#247]
Docs on deleting provenance.

- [x] Python ([`synapseclient.Synapse.deleteProvenance`](http://docs.synapse.org/python/Client.html#synapseclient.Synapse.deleteProvenance))
- [x] R ???
- [ ] Web client also

**Comment by brucehoff** [comment]
@kdaily (and @meredithslota), in the current synapser release candidate there is a synDeleteProvenance() function and reference documentation which is shown when you type "?synDeleteProvenance".   Please check it out and if you feel that this step should be included in the *vignette* as well, kindly let us know (reply to this issue or open a Jira issue).  Thank you.

**Comment by meredithslota** [comment]
@kdaily Can you validate that the documentation @brucehoff is referencing will work for your purposes?

**Comment by meredithslota** [comment]
We are not sure what is possible in the web client re: deleting provenance but we will document what is currently possible as part of this ticket as well.

**Comment by meredithslota** [comment]
Closed w/ https://github.com/Sage-Bionetworks/synapseDocs/pull/355
