### ISSUE TITLE
Please add CORS configuration requirements in the custom external s3 bucket instructions.

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/synapseDocs#248]
http://docs.synapse.org/articles/custom_storage_location.html

**Comment by jay-hodgson** [comment]
You can find the original instructions in version 51 of [this wiki page](https://www.synapse.org/#!Synapse:syn3316305/wiki/194783).

**Comment by meredithslota** [comment]
Closed with https://github.com/Sage-Bionetworks/synapseDocs/pull/302#pullrequestreview-82293308
