### ISSUE TITLE
Need documentation for Project views

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/synapseDocs#249]
Alongside fileviews.html, please name the file projectviews.html (which will be linked to from the project view wizard).

**Comment by kdaily** [comment]
@meredithslota follow up w/ @jay-hodgson to fix link redirect - there's an open Jira somewhere.

**Comment by meredithslota** [comment]
Also need to fix fileviews.html to use the generalized page, views.html, which is already up.

**Comment by meredithslota** [comment]
Filed https://sagebionetworks.jira.com/browse/SWC-4025 for fixing this in the web client, so think this is done.
