### ISSUE TITLE
get paid version of Google search

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#250]
Unfortunate ads show up with some searches (#amiright @meredithslota). These ads (or rather, any ads) make our docs look a tad unprofessional.

**Comment by meredithslota** [comment]
Indeed. 👍

**Comment by meredithslota** [comment]
Note: we don't even need to get the paid version as we are a non-profit. https://support.google.com/customsearch/answer/72361?hl=en cc: @ychae

**Comment by ychae** [comment]
PR #269

**Comment by ychae** [comment]
PR merged.

**Comment by meredithslota** [comment]
This is fixed, yay!
