### ISSUE TITLE
Add in "Public" and "All Synapse Users" Ids to Access Controls article 

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseDocs#252]
Examples for how to programmatically change access settings using the public and all synapse users ids.
273948 -  All Synapse Users
273949 - Public

**Comment by kdaily** [comment]
```
synapseclient.AUTHENTICATED_USERS
273948

synapseclient.PUBLIC
273949
```

**Comment by meredithslota** [comment]
We aren't going to do this; instead, we'll discuss managing permissions programmatically (see #316). Won't Fix.
