### ISSUE TITLE
Need examples of file version (SYNPY-236)

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#253]
We need examples both in the python docs and the getting started guide on how to update an existing file in Synapse. I just responded to an inquiry with:
There are two ways for updating a file an explicit way - fetch the old file (no need to download though) then change the path to the new file and store and an implicit way. Here are two examples:
Explicit Update:
import synapseclient
syn = synapseclient.login()
file_to_update = syn.get(‘syn234’, downloadFile=False)
file_to_update.path = ‘/path/to/new/version/of.file’
updated_file = syn.store(file_to_update)
Implicit Update:
The implicit way of doing it so to push a new file with the same entity name into the same folder (specifically parentId) as an existing file. This will update the version.
#Assume that there is a file created with: syn.store(File(‘path/to/old/file.txt’, name=‘foobar', parentId=‘syn123’) in Synapse
new_file = syn.store(File(‘path/to/new_version/file.txt’, name=‘foobar', parentId=‘syn123’) #Will create a new version of the file
Options

**Comment by ychae** [comment]
PR here: #440

**Comment by meredithslota** [comment]
The linked PR is closed, so closing this.
