### ISSUE TITLE
File views programatic examples

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#254]
Once Python client 1.7 is released add instructions for creating and modifying fileviews

**Comment by kdaily** [comment]
Creating schema is done for views. Need:

1. Edit scope
1. Edit schema

**Comment by meredithslota** [comment]
We added updating scope and schema here: https://docs.synapse.org/articles/views.html#updating-the-scope-or-content-type-of-a-view and programmatic updates will live in the client documentation.
