### ISSUE TITLE
Python client 1.7

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#255]
Verify all changes to synapseclient version 1.7 that require documentation changes.

**Comment by zimingd** [comment]
We also need an update on 
http://docs.synapse.org/articles/custom_storage_location.html
in the "Adding Files in Your S3 Bucket to Synapse" section
users no longer need to manually create the a dict for uploading an S3FileHandle they can just do:
`synapseclient.File('path/to/file.txt' ,parentId=PROJECT)`

**Comment by meredithslota** [comment]
@zimingd Is that the only change you've identified so far in the main articles? If so, I can take this one.

**Comment by kdaily** [comment]
Hello, @zimingd? Can you confirm, please? Thanks in advance!
