### ISSUE TITLE
explain external repositories for Docker

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#258]
In the web client, there's a button for "Add External Repository" with no documentation. We should document this. There's a Jira issue to add contextual help in the Synapse Docker tab as well (SWC-3688).

**Comment by jay-hodgson** [comment]
Once [docker documentation](http://docs.synapse.org/articles/docker.html) contains information about external repos, please let me know in [SWC-3688](https://sagebionetworks.jira.com/browse/SWC-3688) and I'll add a help widget.  Thanks!

**Comment by meredithslota** [comment]
@thomasyu888 This is currently assigned to you -- do you have a draft or shall we reassign?

**Comment by thomasyu888** [comment]
https://github.com/Sage-Bionetworks/synapseDocs/commit/8c0284d80dfb92079fb96ea64dcef11df28d7dfa
