### ISSUE TITLE
add synDownloadTableColumns to R client tables vignette

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#260]
http://docs.synapse.org/r/synDownloadTableColumns.html

moved from

https://sagebionetworks.jira.com/browse/SYNR-1050

**Comment by kimyen** [comment]
The work is done. The vignette can be found here: http://sage-bionetworks.github.io/synapser/articles/tables.html#table-attached-files

At the end of this section, there is code showing `synDownloadTableColumns()` in action.
