### ISSUE TITLE
Updates for annotation_and_query.md and fileviews.md

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/synapseDocs#264]
Some of the contents from this wiki page can be added to the docs site.
[https://www.synapse.org/#!Synapse:syn7444884/wiki/449471](https://www.synapse.org/#!Synapse:syn7444884/wiki/449471)

**Comment by meredithslota** [comment]
I will triage this content and assess what can be migrated vs. just deleted.

**Comment by kimyen** [comment]
@xindiguo , File Views vignettes and code instructions should be available in R client docs and in Python client docs now. Synapse Docs about Views should links to the R and the Python client docs. 
It looks like most of the content has been moved except for one code block.

**Comment by kelshmo** [comment]
Closing based on @kimyen's comments.
