### ISSUE TITLE
Create a Synapse in Practice or Synapse Vignettes section

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#265]
We have realized that there are examples of how to use Synapse in practice.  Like vignettes and examples.  At the start we could create:

- [ ] Mette's How to setup your community 
- [x] Annotations vignettes from 
- [x] Abhi's working with sequence files
- [ ] Lambda files.

**Comment by sgosline** [comment]
What do people think about
- [ ] using project views to group projects
- [ ] creating wikis with public and private content

**Comment by meredithslota** [comment]
What we are committing to for the June 2018 milestone is the following: 

1. Creating the section
2. Adding articles for the existing content. Only these topics have existing content prepped: 
- [ ] How to Setup a Community
- [ ] Annotations wiki content for using annotator + synapseutils (@xindiguo content?)
- [ ] Abhi's working with sequence files (@ychae to confirm existence of content)

Lambda files are not ready re: content so are out of scope for this work for now, and @sgosline, if you have content for the items you suggested, let us know!

**Comment by xindiguo** [comment]
Here is the link to the wiki page - 
https://www.synapse.org/#!Synapse:syn7444884/wiki/411693

**Comment by meredithslota** [comment]
@kdaily has the content for sequence stuff, he is working on generalizing @apratap's content.

**Comment by meredithslota** [comment]
@ychae Do we have content for the "How to Setup a Community" from @amapeters yet?

**Comment by ychae** [comment]
Not yet. I'll follow up again!

**Comment by ychae** [comment]
The closest doc I could find is the one one called: [Communities Data Release SOP Working Document](https://docs.google.com/document/d/1XmuMx_CtV94Zq-KBNln8cuYCJKaJfDRvVLXHkth3Mik/edit#heading=h.busgfth3i3w)

**Comment by kdaily** [comment]
Closing this and opening a separate issue to make a vignette for 'how to set up your community'.

**Comment by kdaily** [comment]
Opened #645 to finish this work, closing.
