### ISSUE TITLE
Create documentation about user authenticated S3 storage location

### ISSUE THREAD

**Issue by zimingd** [Sage-Bionetworks/synapseDocs#266]
Synapse will not have access to these S3 buckets. It will simply record metadata about where the files are located. The user must provide AWS credentials to the client they are using in order to upload/download these files

**Comment by meredithslota** [comment]
@zimingd Is this for the external object store functionality?

**Comment by kelshmo** [comment]
[Documented](https://docs.synapse.org/articles/custom_storage_location.html).
