### ISSUE TITLE
make challenge template easier to learn

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#271]
Move of [SYNPY-379](https://sagebionetworks.jira.com/browse/SYNPY-379) 

During the ENCODE challenge we learned that the assigned programmer, Nathan, struggled to spin up with the Python challenge template. He asked for a step by step recipe to adapt the template to be a scoring app.
From Nathan:
IMHO, the easiest way to present these ideas would be to refactor the current tutorial so that there is:
1) a script that creates the administrative and systems users and creates the submission queue
2) a totally separate script that scores and grades submissions
In other words, I expect that most users will create the wiki using the edit features in the their web browsers, and then perform the scoring programmatically. The way that the tutorial is currently structured makes it difficult to see where one ends, and the other begins. 
...
In the document
https://www.synapse.org/#!Synapse:syn2453886/wiki/63969
I think that the "Create a Scoring Application" needs to be expanded.
Other specific items to address:
need to provide an overview of how to score, with best practices. This includes the list things to create in Synapse, the architecture (i.e. that scoring app's are outside Synapse, interfacing via the Synapse API), etc. The overview should include a description of the various principals involved, incl. the service acct running the scoring app, the sign up team for the challenge, the participant users, the participants' teams (that they form among themselves), the team of challenge organizers.
explain that programmer should set up a service account to run the scoring app. this account need not have Admin access. Can Score access would suffice.
needs to be clear that scoring app does not set up or tear down wikis it just publishes annotations
The existing documentation is in two places. (1) A Synapse wiki:
https://www.synapse.org/#!Synapse:syn2453886/wiki/63969
(2) the read me and inline doc's for the template code itself
https://github.com/Sage-Bionetworks/SynapseChallengeTemplates
NOTE: There is another effort to consolidate documentation to docs.synapse.org, so consider aligning with this effort.

**Comment by meredithslota** [comment]
We'll do this work as part of the challenge retro and post mortem conversation as we want to improve more pieces of documentation as well to start to clarify best practices. Putting in the Sept. 2018 milestone, we may bump it up if we get content early.

**Comment by meredithslota** [comment]
@thomasyu888 has done a lot of work here, so in lieu of more specific requirements, I'm going to assume this is done. Closing.

If you have more specific requests for improvements, let's open a new issue!
