### ISSUE TITLE
make docs.synapse.org https

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#279]
Upcoming versions of browsers (Chrome of note) are going to, by default, show warnings for non https pages. We should get ahead of that.

**Comment by meredithslota** [comment]
@ychae How do we do this? Do you need something from Xa or similar to make this happen?

**Comment by meredithslota** [comment]
I'll follow-up with @xschildw to make this happen.

**Comment by meredithslota** [comment]
This is being tracked as an engineering item, here: https://sagebionetworks.jira.com/browse/PLFM-4720 @kdaily Ok to close this issue? If not, plz reopen.
