### ISSUE TITLE
Short intro article for uploading data

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#281]
to match the download intro article.

**Comment by kdaily** [comment]
Also, maybe will go away/roll into "files and versioning" and/or "bulk upload"?

**Comment by ychae** [comment]
So this seems to be pretty well covered in the [Batch Processing article](https://docs.synapse.org/articles/uploading_in_bulk.html). @meredithslota Do you think that article is sufficient?

**Comment by kdaily** [comment]
This is done in the sense that the pages are written. #546 discusses how to reorganize the content.
