### ISSUE TITLE
update table article to user synapser instructions instead of (old) R client

### ISSUE THREAD

**Issue by kimyen** [Sage-Bionetworks/synapseDocs#283]
I'm working on this:
https://github.com/Sage-Bionetworks/synapser/blob/master/vignettes/tables.Rmd

**Comment by kdaily** [comment]
@meredithslota  I vote we close this for now, because it's part of a larger issue of documenting the new R client across the docs page?

**Comment by meredithslota** [comment]
This is to update http://docs.synapse.org/articles/tables.html after the release of the synapser client, which is soon. Adding to June 2018 milestone.

**Comment by kimyen** [comment]
I think this PR also address this issue: https://github.com/Sage-Bionetworks/synapseDocs/pull/330

**Comment by kimyen** [comment]
The PR is merged.
