### ISSUE TITLE
Please remove the wiki-based page on how to create a challenge in Synapse

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#285]
From an email thread:

Me to Tom:
```
I heard you have reworked the content of this challenge set up guide,

https://www.synapse.org/#!Synapse:syn2453886/wiki/63969

and put the content elsewhere.  Is that true?  If so, that's great.  Should we remove the former and replace it with a pointer to your new site?  I have recently made changes to the wiki and would need to merge the changes with your doc's.

```

Tom to me:

```
Dear Bruce,

Here are the pull requests for the challenge docs:  

Challenge admin: https://github.com/Sage-Bionetworks/synapseDocs/pull/207
Participation in challenges: https://github.com/Sage-Bionetworks/synapseDocs/pull/223

I have cc'ed Yooree, because she is working on pulling these in.  

```

We should aim to have one, authoritative source of documentation by replacing the content of this wiki page with a URL link to the "official" documentation, after first ensuring there is nothing in the wiki page that is missing from said documentation.

**Comment by ychae** [comment]
There need to be language updates and grammar checks, along with a few
changes that were requested by Kenny.

**Comment by meredithslota** [comment]
The "Challenge Administration" wiki content has been migrated to http://docs.synapse.org/articles/challenge_administration.html, and I'll update the Synapse "standalone wiki" page to reflect that. HUZZAH!

**Comment by brucehoff** [comment]
@meredithslota This issue needs to be reopened:  Content in the Synapse-based page was lost in the change that you made.  Version 58 of https://www.synapse.org/#!Synapse:syn2453886/wiki/63969 needs to be merged into the new page to preserve it. For example, an important section,  "Share participants' email addresses with DREAM" from the Synapse wiki is lost in the new page.
