### ISSUE TITLE
Add documentation on searching for users using the "@" symbol

### ISSUE THREAD

**Issue by heymeredith** [Sage-Bionetworks/synapseDocs#286]
There's existing documentation re: http://docs.synapse.org/articles/teams.html#finding-teams BUT we don't specify that you can also use that method to find individuals. I'd like to try to close out https://sagebionetworks.jira.com/browse/PLFM-1635 with user guidance instead of reworking the search tools at this point. Let me know if you'd like assistance writing the doc?

**Comment by meredithslota** [comment]
Negated by a change to the platform to include guidance inline on the search page.
