### ISSUE TITLE
Update Custom storage location example code for Python

### ISSUE THREAD

**Issue by zimingd** [Sage-Bionetworks/synapseDocs#287]
http://docs.synapse.org/articles/custom_storage_location.html

Once the Python client v1.7.3 releases, users no longer have to make dicts and perform manual rest API calls. Instead they can use `syn.createStorageLocationSetting()` and `syn.applyStorageLocationSetting()` to create and set custom storage locations. 

Please update the example code to use these methods instead when v1.7.3 releases. If you have any questions about using these methods, feel free to contact me.

**Comment by meredithslota** [comment]
This article needs a broader update, which I will take on, and @ychae will help me ensure that the Python code example is accurate.

**Comment by kelshmo** [comment]
Resolved.
