### ISSUE TITLE
Request doc page for Wiki Order tool

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/synapseDocs#289]
New page should live here: http://docs.synapse.org/articles/edit_wiki_order.html

Related to https://sagebionetworks.jira.com/browse/SWC-2937

Proposed interaction in Synapse can be seen here:
https://www.youtube.com/watch?v=l73GYyY-akY&feature=youtu.be

**Comment by meredithslota** [comment]
We are adding content re: editing order to the main "Wikis" page instead (not enough content to warrant a separate page). URL is here: http://docs.synapse.org/articles/wikis.html Pull request is here: https://github.com/Sage-Bionetworks/synapseDocs/pull/293
