### ISSUE TITLE
out of date documentation

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#291]
from @kdaily 
```
out of date documentation


[8:02] 
"Setting fileNameOverride will not change the name of a copy of the file that’s already downloaded into your local cache."


[8:02] 
http://docs.synapse.org/python/Entity.html#changing-file-names


[8:02] 
Read it too fast


[8:03] 
Makes me think that filenameOverride still does something
```

**Comment by meredithslota** [comment]
@brucehoff Don't the Python docs get auto-generated by the Python client? If so, I'm going to open up a JIRA ticket for this instead and close out this GitHub issue. cc: @zimingd is that correct?

**Comment by brucehoff** [comment]
> Don't the Python docs get auto-generated by the Python client?
Yes, the Python reference doc's (everything under http://docs.synapse.org/python/, I believe) are generated from content in the Python source code. @zimingd can correct me if I'm wrong.

**Comment by meredithslota** [comment]
Not sure what the change should be, but ultimately this should be a ticket in JIRA for the Python client. @brucehoff if this still needs to be done, can you clarify so we can move this to JIRA?
