### ISSUE TITLE
document how to craft markdown in Python and R

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#295]
Per @kdaily there is a need to document how to craft markdown in Python and R, esp. how to include escape character, new lines, etc., so that content appears as expected in the web portal.

**Comment by kdaily** [comment]
Should go here:

http://docs.synapse.org/articles/wikis.html

**Comment by meredithslota** [comment]
Added to June 2018 milestone to get an initial draft up.

**Comment by meredithslota** [comment]
Assigning to @kimyen and @kdaily to write simple markdown examples.

**Comment by meredithslota** [comment]
We fixed the newline issue with CSS -- it was never a problem with newlines, it was always a problem with not enough padding. This is not longer needed. :)
