### ISSUE TITLE
Tables document has non-working reference to vignette

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/synapseDocs#310]
At the bottom of the tables page is this: 

```For R, open up your R session and check out our vignettes by typing vignette("tables", package="synapseClient") into your console.```

However, when I follow these instructions in R:
```> vignette("tables", package="synapseClient")
Warning message:
vignette ‘tables’ not found 
```

**Comment by kdaily** [comment]
https://sagebionetworks.jira.com/browse/SYNR-1135
