### ISSUE TITLE
programmatic setting of permissions

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#316]
Started from #252 

Need to add to here for now because that's where it is:

http://docs.synapse.org/articles/access_controls.html

**Comment by kdaily** [comment]
Probably a new article on "Managing access controls".

**Comment by meredithslota** [comment]
Considering this done w/ #252. If there are additional needs, let's make a new issue.

**Comment by meredithslota** [comment]
Whoops. Misunderstood links. Reopening.

**Comment by kelshmo** [comment]
@Aryllen we do this to [set up a project for the dccvalidator](https://github.com/Sage-Bionetworks/dccvalidator/blob/master/inst/app/create_project.R) or with `synapser` [here](https://github.com/Sage-Bionetworks/PEC-DCC/blob/master/tools/portal/make_project.R). Could we add these code chunks to a new section "Managing access controls" on [this page](https://docs.synapse.org/articles/access_controls.html). We may migrate to the R/python client respectively.

**Comment by kelshmo** [comment]
Programmatic things are going to live in respective client docs.
