### ISSUE TITLE
Promote the use of Jupyter notebooks in Challenges

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#318]
Much has been done in recent months to better integrate Jupyter notebooks into Synapse.    I'm opening this issue to suggest that their use could be promoted in DREAM Challenges as a way participants can write up their methods.  To do this:
1) Edit Sect. 3.9 of the challenge wiki template (https://www.synapse.org/#!Synapse:syn2769515/wiki/448126) to talk about using Jupyter notebooks and perhaps providing links to samples;
2) Give a demo at the biweekly DREAM Directors meeting to show how they enhance communication of methods used in challenges.

**Comment by meredithslota** [comment]
I don't think we'll do this as-is -- in discussing this with Challenge admins, it's not clear that Jupyter notebooks would be a preferred submission vehicle. That said, we should list out the items for which we support rich previews, here: https://docs.synapse.org/articles/files_and_versioning.html#file-previews. Closing this in favor of #439
