### ISSUE TITLE
Need clarification on setting up ARs for challenges to support extended use cases

### ISSUE THREAD

**Issue by meredithslota** [Sage-Bionetworks/synapseDocs#319]
As per https://sagebionetworks.jira.com/browse/PLFM-4569, need to provide documentation on setting up challenges so that proper permissions checks are created natively. cc: @kimyen and @ychae

**Comment by meredithslota** [comment]
@kimyen I no longer really know what this is for. Do you?

**Comment by kimyen** [comment]
I do. Challenges normally has some requirements on submissions. Previously, @ychae needs to add script to check the requirements. If the challenge was setup correctly in the first place, no additional script is needed.

**Comment by kelshmo** [comment]
I don't have any insight into the scripts referenced here. Closing due to a misplaced transfer of knowledge.
