### ISSUE TITLE
Update all instance of R code examples to use synapser examples

### ISSUE THREAD

**Issue by meredithslota** [Sage-Bionetworks/synapseDocs#323]
Steps: 
1. Search repo folder /articles for "{% tab R %}" 
2. Find 58 examples
3. Work with someone who knows R to fix each

Sample issue is #283.

**Comment by meredithslota** [comment]
@kdaily and @ychae

**Comment by kimyen** [comment]
All synapser_0.1 issues are resolved, so I am going to work on this.

**Comment by kimyen** [comment]
https://github.com/Sage-Bionetworks/synapseDocs/pull/330

**Comment by kimyen** [comment]
The PR is merged. I am not sure how "validation" works in Github issues. I will close this ticket, but please reopen if you disagree. Also please let me know if someone else should close tickets assigned to me. Thanks.
