### ISSUE TITLE
File Preview - ? mark for more info

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/synapseDocs#328]
The ? mark for more info in the file preview window leads to a description about sharing setting.  It would be very useful if it also linked to a list of file formats visible in the preview

**Comment by kdaily** [comment]
Where in the Synapse docs page does that happen? I think this needs to be a Jira issue...

**Comment by amapeters** [comment]
It's the ? mark in the preview window. When you click on more info
![screen shot 2018-02-12 at 3 05 34 pm](https://user-images.githubusercontent.com/2660103/36124769-3d407954-1006-11e8-8272-49b6276560c9.png)

**Comment by amapeters** [comment]
Do we have documentation on what formats are visible in the preview?

**Comment by meredithslota** [comment]
Not yet.

**Comment by meredithslota** [comment]
Updated the doc in #397 and also created https://sagebionetworks.jira.com/browse/SWC-4294 to update the link.
