### ISSUE TITLE
Update the custom storage article - S3 bucket

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/synapseDocs#331]
I was working on a project that required linking files from an S3 bucket outside of Sage. Here are some suggestions/comments @kdaily and I came up with:
- We should mention that it works for all region (the files I worked with are in eu-central)
- owner.txt is required for READ-ONLY permission as well, otherwise, you cannot set the S3 as upload location
- ```"s3:*MultipartUpload*``` should be removed from the Read-only permission's bucket policy
- When setting up the S3 bucket in the Synapse folder/project, the `Base Key` has to end with a "/" since the current code does not check for that ([PLFM-4861](https://sagebionetworks.jira.com/browse/PLFM-4861))

**Comment by kelshmo** [comment]
@xindiguo Can you check [this article](https://docs.synapse.org/articles/custom_storage_location.html) and comment on whether is hits on those bullet points listed above?

**Comment by kelshmo** [comment]
See [Custom Storage Locations](https://docs.synapse.org/articles/custom_storage_location.html)
