### ISSUE TITLE
Figure out and document where REST, R, and python docs originate

### ISSUE THREAD

**Issue by meredithslota** [Sage-Bionetworks/synapseDocs#335]
How do we do? We don't know. Figure it out and write it down.

**Comment by kimyen** [comment]
R docs: https://sagebionetworks.jira.com/wiki/spaces/SYNR/pages/151420929/synapser+dev+staging+validation+release#synapserdev/staging/validation/release-PublishingDocumentation
Python docs: https://sagebionetworks.jira.com/wiki/spaces/SYNPY/pages/643498030/Synapse+Python+Client+Staging+Validation+Production#SynapsePythonClientStaging/Validation/Production-Documentation

**Comment by kelshmo** [comment]
Xa took care of redirects to the client docs and we took care of documenting that [in the README here](https://github.com/Sage-Bionetworks/synapseDocs#linking-to-synapse-client-documentation). hooray!
