### ISSUE TITLE
article on Synapse Forms

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#338]
Question from the forum, we should document:

https://www.synapse.org/#!Synapse:syn5637528/discussion/threadId=3106

**Comment by kdaily** [comment]
It's in aloha mode, soooo...

**Comment by ychae** [comment]
Err alpha mode, you mean?

**Comment by meredithslota** [comment]
Draft in progress, ETA 2-3 days. Needs to be done before https://sagebionetworks.jira.com/browse/SWC-3893 hits production! :)

**Comment by meredithslota** [comment]
See pull request #365.
