### ISSUE TITLE
Create a File View screencast is out of date

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseDocs#340]
In the [file view documentation](http://docs.synapse.org/articles/views.html) there's a [screencast](https://youtu.be/qWjVlw2_n2w) that shows buttons for "Add Table", "Upload Table", and "Add File View" underneath the Wiki/Files/etc. tabs; these buttons are now within the Tools menu on the right.

**Comment by meredithslota** [comment]
We are not going to update this just yet; will do an overall refresh once we revise the look and feel of file pages, etc.

**Comment by kelshmo** [comment]
PR #614 to remove link.
