### ISSUE TITLE
Fixed Google custom search CSS

### ISSUE THREAD

**Issue by meredithslota** [Sage-Bionetworks/synapseDocs#352]
Currently looking a little bit broken.

**Comment by ychae** [comment]
Is this related to Kenny's issue? #367

**Comment by meredithslota** [comment]
Looks even MORE broken today, screenshot: 
![broken-search-box](https://user-images.githubusercontent.com/5223152/40505867-7382ec3e-5f4a-11e8-8ddd-772432a34729.jpeg)

Assigning to myself to look at over the weekend.

**Comment by meredithslota** [comment]
It seems fine now. We'll need to do a whole design pass when new Synapse styles launch so this is fine for now.
