### ISSUE TITLE
internal wiki links

### ISSUE THREAD

**Issue by lpagie** [Sage-Bionetworks/synapseDocs#353]
it took me quite some time to figure out how to use internal links to other wiki pages. Now I understand that adding something like `syn12041053/wiki/519577` to a wiki page creates a link to a wiki page in project 12041053, and wiki page is sub page 519577. The only way I know to find the number of the sub page is to check the URL in the browser when that page is active/open.
I think some sort of documentation of this feature might help. But I am a bit puzzled where the source of the documentation is:
this page `https://github.com/Sage-Bionetworks/synapseDocs/blob/master/articles/wikis.md` is not `http://docs.synapse.org/articles/getting_started.html#adding-a-wiki-to-your-project`. So I'm not sure where to add any clarification.

A possible clarification could be something like:

> Internal links to other (sub-)wiki pages are of the form `syn12041053/wiki/519577`, where the first part  (`syn12041053`) specifies the project, the `wiki` part specifies you link to the root-page of that project's wiki, and the last part (`519577`) refers to the sub-page `519577` of that wiki. The number of the subpage can be found in the browser's location bar when the sub-page is viewed.

**Comment by meredithslota** [comment]
Hello @lpagie -- thank you for submitting an issue! I've taken this one on and we'll commit to getting it done by June (adding to June milestone).

**Comment by meredithslota** [comment]
The relevant content is in the article on Wikis, here: http://docs.synapse.org/articles/wikis.html -- this is linked to from the Getting Started article, but is more in-depth. I've added the suggested content almost verbatim; thank you for suggesting this, @lpagie.
