### ISSUE TITLE
change search text box

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#367]
Why does it say "Custom S" (if zoomed out it says "Custom Search"). We should replace it with something else, even just "Search" and make sure the whole text is visible at any zoom (left justified).

![screenshot from 2018-05-01 09-02-14](https://user-images.githubusercontent.com/84993/39480896-81cbd898-4d1e-11e8-9da8-f7fa83cb7251.png)

**Comment by ychae** [comment]
see PR #374

**Comment by ychae** [comment]
Addressed by PR #374
