### ISSUE TITLE
non-functional menu items

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#371]
Visit: http://docs.synapse.org/
Click on 'Getting Started' (at top)
Result:  Nothing happens
Click on 'API Docs'
Result:  No menu appears

**Comment by kdaily** [comment]
Just tested in Google Chrome on Linux and both of those work?

**Comment by brucehoff** [comment]
I neglected to provide the platform:  The problem is on Chrome on MacOS.  Works on Firefox and Safari.

**Comment by ychae** [comment]
Hi Bruce, I'm on Chrome Version 66.0.3359.170 (Official Build) (64-bit) on MacOS and it looks to be functioning as expected.

**Comment by brucehoff** [comment]
I upgraded Chrome to *.170 and the problem stopped.  Don't know if it was fixed by my upgrade or for some other reason but I will close the issue.
