### ISSUE TITLE
Synapse logo out of date

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#38]

**Comment by kdaily** [comment]
In the image mapping b/t Synapse and clients, uses old yellow Synapse logo

**Comment by kdaily** [comment]
I made a new logo, need to fix the existing images to use this logo.

**Comment by larssono** [comment]
Sarah M is working on new images.

**Comment by kdaily** [comment]
Hooray! My mediocre GIMP skills are not needed.
