### ISSUE TITLE
Link to legacy R client doc

### ISSUE THREAD

**Issue by kimyen** [Sage-Bionetworks/synapseDocs#387]
The new look for the doc site is refreshing. I was excited to click around. :) 
I notice that on this page: http://docs.synapse.org/articles/api_documentation.html, the R client doc link is going to the legacy client. Is this intentional?

**Comment by ychae** [comment]
Whoops, nope! I have a PR that's a redesign of the API page. I'll update the link so that it goes to the correct R client page.

**Comment by kimyen** [comment]
Thanks @ychae !

**Comment by meredithslota** [comment]
Closed w/ #383
