### ISSUE TITLE
Wiki help including link to markdown

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#39]

**Comment by larssono** [comment]
Create a wikis.md file and add an overview of what a wikis are and links to documentation for markdown.  

Include help on widgets and examples on widgets avaialable.  Should probably contain screenshots of examples of widgets being used.

**Comment by larssono** [comment]
@sgosline will you reassign to Mette when you are done.

**Comment by sgosline** [comment]
I've done as much as I can, after pull request is accepted then @amapeters can take a look at it.

**Comment by philerooski** [comment]
If every (or most) challenges require a write-up to be done within the wiki (and if we expect a significant proportion of users to become familiar with Synapse via participation in DREAM challenges), there should be a brief statement in the Overview section about the requirement. A sort of "why should I care if I just came here to do data science on science and am not particularly interested in giving my model a rigorous documentation for others to reproduce" kind of statement.

**Comment by amapeters** [comment]
I don't think that belongs in the general wiki description, but something that is communicated in each challenge documentation

**Comment by kdaily** [comment]
Should probably go somewhere else, but not specific to challenges - our
view of "why do open things" in general (which is probably in the Sage site
somewhere).

**Comment by larssono** [comment]
Code examples are missing linefeeds
