### ISSUE TITLE
script imports should not be hard-coded to http (moving docs site to https)

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/synapseDocs#405]
Example error is:
Mixed Content: The page at 'https://docs.synapse.org/' was loaded over HTTPS, but requested an insecure script 'http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/additional-methods.min.js'. This request has been blocked; the content must be served over HTTPS.

For example, 
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.js"></script>
should be changed to
<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.15.0/jquery.validate.js"></script>

**Comment by ychae** [comment]
done.
