### ISSUE TITLE
Fix "search" to index proper new documentation locations

### ISSUE THREAD

**Issue by meredithslota** [Sage-Bionetworks/synapseDocs#415]
With the migration of the R and Python docs, "search" is bringing back broken links. 

For example, searching for "python" brings up the following results: 

![image](https://user-images.githubusercontent.com/5223152/44737760-b81d7a00-aaa7-11e8-9ec3-d23afeed6f35.png)

Only the first link works and redirects; the latter 4 of 5 are all broken.

**Comment by ychae** [comment]
@meredithslota I've updated the search engine to exclude `docs.synapse.org/python/*` and `docs.syanpse.org/r/*`. Hopefully this does the trick!

**Comment by ychae** [comment]
![google_cse](https://user-images.githubusercontent.com/12868382/44738331-7988bf00-aaa9-11e8-8e53-1582f0012e07.png)

**Comment by meredithslota** [comment]
How long will it take to reindex? Is there a way to force reindexing? I'm still seeing the issues.

**Comment by ychae** [comment]
I think we can force a re-indexing but we have to submit the request to the Google Console, rather than CSE. I'm working on that now and I'll keep you updated.

**Comment by ychae** [comment]
@meredithslota please test again. I'm seeing the correct behavior now on my end.

**Comment by meredithslota** [comment]
I see it now too! Fixed. YAY!

**Comment by meredithslota** [comment]
We missed the API docs! Reopening to add those. cc: @ychae

**Comment by ychae** [comment]
AH! Added https://docs.synapse.org/rest/ so we should be getting the REST docs now.
