### ISSUE TITLE
change wording for facets description

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#421]
@ychae noted that we suggest that there are sliders for range fields, but we only have selection boxes.

**Comment by meredithslota** [comment]
We have selection boxes and sliders -- if you do it on an integer, it's a slider. If you do it on a timestamp, it's a selection box so that users can use the date picker. Example: https://www.synapse.org/#!Synapse:syn16226668/tables/

**Comment by meredithslota** [comment]
Uh, there's no "Won't Fix" in github issues but this is that.
