### ISSUE TITLE
Document how to handle single quotes in a synapse table/fileview query

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseDocs#423]
Need to document how to handle single quotes in a Synapse query. For example, if there is a single quote in the value (like you see in chemical structure names) it needs to be replaced by a double quote:

```
chemicalStructure = 4'-somethingsomething
```

would be queried as:

```
SELECT * FROM syn123 where "chemicalStructure" = '4"-somethingsomething'
```

**Comment by ychae** [comment]
Also another way is to use **two** single quotes instead of the double quote

```
SELECT * FROM syn123 where "chemicalStructure" = '4''-somethingsomething'
```

**Comment by kelshmo** [comment]
updated!
