### ISSUE TITLE
error in license info (Is synapse open source)

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseDocs#428]
https://docs.synapse.org/articles/faq.html#is-synapse-open-source

Synapse (and the 3 clients) are licensed under Apache-2.0, not MIT; this came up on an external call today.

**Comment by kdaily** [comment]
@allaway @sgosline you should open a Jira issue for guidance and a strategy for how to refer to Synapse licensing, as we have multiple repositories for components of Synapse (beyond the R and Python clients) that are all under Apache 2.0. We should have a page dedicated to that (maybe we do, buried somewhere).

It should also include copy that content on Synapse is under [Creative Commons Attribution 4.0 International Public License](https://creativecommons.org/licenses/by/4.0/legalcode) which might also be important to tell lawyers and the like.
