### ISSUE TITLE
Remove docs/ part of docs related to the deprecated query services

### ISSUE THREAD

**Issue by kimyen** [Sage-Bionetworks/synapseDocs#436]
One instance is here: https://docs.synapse.org/articles/annotation_and_query.html#queries
We should check everywhere in the docs.

I think it's possible to replace the instruction with the use of EntityViewSchema or `syn.getChildren`.

Tagging @meredithslota to triage this ticket to match with the deprecation plan.

**Comment by kimyen** [comment]
@kelshmo is working on this, I believe. I am adding your name to the assignees so that you can close this one when you are done with your work.

**Comment by kelshmo** [comment]
updated!

**Comment by kimyen** [comment]
I found one that has not been converted: https://docs.synapse.org/articles/annotation_and_query.html
```
SELECT specimenID,genomeBuild,fileFormat,platform FROM file WHERE "projectId"='syn00123' AND "specimenID"='sampleA_conditionB'
```

**Comment by kimyen** [comment]
And: https://docs.synapse.org/articles/annotation_and_query.html#how-to-download-based-on-queries
```
synapse get -q "SELECT * FROM file WHERE parentId = 'syn00123'"
```
