### ISSUE TITLE
Link to Python/ synapser docs for code examples

### ISSUE THREAD

**Issue by kimyen** [Sage-Bionetworks/synapseDocs#443]
The Python and synapser code examples are easier to keep up-to-date with the client release cycle. The Synapse docs may content high level overview of a feature, but should link to the Python docs and synapser docs for the actual code. 
This suggestion, once implement, would help us cut off a step in updating the docs for code examples when releasing a client.

**Comment by meredithslota** [comment]
Items found so far that could be linked to directly w/ code examples removed from main site:

Docker Basics: https://r-docs.synapse.org/articles/docker.html, https://python-docs.synapse.org/build/html/Entity.html?highlight=docker#synapseclient.entity.DockerRepository (but that link links back to docs site!)

Tables: https://r-docs.synapse.org/articles/tables.html, https://python-docs.synapse.org/build/html/Table.html

Let's start there!
