### ISSUE TITLE
Use Github Pages instead of copy content to S3

### ISSUE THREAD

**Issue by kimyen** [Sage-Bionetworks/synapseDocs#444]
This repository contains markdown files, html files and setup to build with Jekyll. Github Pages supports exactly that: https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/

Once configured as a Github Pages (with https), this repository will be available at https://sage-bionetworks.github.io/synapseDocs

Adding a CNAME file containing "https://docs.synapse.org" and configure Route 53 correctly will allow us to host the docs on Github Pages. We can cut off a step of copying the html files to an S3 bucket.

**Comment by kimyen** [comment]
The approach is to move code blocks to client docs. After all client docs is created, the original docs can link to client docs.
In the mean time, we can also expand code block outside of `tab`.
When we get to the point where no javascript is required, we can turn on Github Pages build.

**Comment by kelshmo** [comment]
@Dumindaaa language describing technical requirements.

**Comment by kdaily** [comment]
Process is done - need to point address at new site.
