### ISSUE TITLE
Update instructions in update-annotations-in-bulk

### ISSUE THREAD

**Issue by kimyen** [Sage-Bionetworks/synapseDocs#447]
Per @karawoo, 

> I think this section needs a note that the steps do not work for adding new annotations. I think it’s already been reworded once but could be more explicit still. https://docs.synapse.org/articles/views.html#update-annotations-in-bulk

**Comment by karawoo** [comment]
I wrote a function that will add new annotations to a file view here: https://github.com/Sage-Bionetworks/syndccutils/blob/master/R/R/add_fileview_annotations.R

However I would hesitate to recommend it on the docs site to external users without more testing and official support (syndccutils is used internally but not by external users as far as I know). The other option is to iterate over the files and first get the annotations, then add new annotations, then save them with `synSetAnnotations`. This can be pretty slow and one must be careful not to overwrite existing annotations (see https://sagebionetworks.jira.com/browse/SYNPY-861)

**Comment by meredithslota** [comment]
I think we should discuss w/ @kimyen because updating and managing annotations at scale will be a major focus for the next versions of the clients. What is syndccutils?

**Comment by karawoo** [comment]
It's a collection of R and Python code that various people across comp onc and sys bio have written for doing data coordination work, stored in one place to try to reduce the duplication of effort on similar problems.

**Comment by kelshmo** [comment]
Explicit note added to Annotations docs page
