### ISSUE TITLE
change 'Bulk Processing' to 'batch processing'

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#451]
Because that's what the article is called.

https://docs.synapse.org/articles/uploading_in_bulk.html

Larger issue: determine if this is 'bulk' or 'batch' and be consistent.

**Comment by meredithslota** [comment]
Where does it say "batch"?

**Comment by kdaily** [comment]
https://docs.synapse.org/articles/

![screenshot from 2018-10-22 13-37-18](https://user-images.githubusercontent.com/84993/47317960-a36ce680-d5ff-11e8-8b9c-b70bec5cd4cc.png)

Also not clear in the description that it's also about download, not just upload.

**Comment by meredithslota** [comment]
OH. Weird! That "Batch Processing" article goes to a different page: https://docs.synapse.org/articles/uploading_in_bulk.html -- I'm not sure what this ticket is asking for then?

**Comment by meredithslota** [comment]
(In general, "batch" is kind of a specific technical word but "bulk" is not.)

**Comment by kdaily** [comment]
Oops - pasted wrong url. Indeed it's that one: https://docs.synapse.org/articles/uploading_in_bulk.html

**Comment by kelshmo** [comment]
fixed this
