### ISSUE TITLE
Anonymous Wiki viewing

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#455]
Improve documentation of anonymous viewing of Wiki. https://docs.synapse.org/articles/accounts_certified_users_and_profile_validation.html

Also, amend this documentation to the wiki section. 
https://docs.synapse.org/articles/wikis.html

**Comment by kdaily** [comment]
Unsure if we can change the table, as it is what is displayed in the [Data Use Procedure](https://s3.amazonaws.com/static.synapse.org/governance/SynapseCommonsDataUseProcedure.pdf?v=4).

**Comment by kdaily** [comment]
There's a sentence in the intro of the wiki article. Let's wordsmith that, and link to the sharing settings page.
