### ISSUE TITLE
Need consistent character encoding for docs

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/synapseDocs#459]
One of my PRs (#456) failed the tests because there's a mix of encodings (UTF-8 and ASCII-8BIT).

We should agree to a consistent character encoding to avoid these problems. I suggest UTF-8.

**Comment by kdaily** [comment]
Good suggestion! can we test for this with travis?

**Comment by philerooski** [comment]
I'm not sure. From what I understand checking the encoding of a file is not easy.

**Comment by philerooski** [comment]
Interestingly, I ran
```
:set fileencoding utf-8 # it was already utf-8, but just to make sure
:set bomb # byte order mark
```
before writing the file in vim and Travis quite complaining.

**Comment by meredithslota** [comment]
Just checking -- we have different article templates and the markdown gets piped into those templates to be turned into HTML. Not all the templates had a UTF-8 declaration, and some of the other formatting was different, so I'm gonna test normalizing those first in #492.

**Comment by meredithslota** [comment]
Checking -- have we seen any issues with this since #492 was accepted? I haven't seen any, so I'm going to close this, but if you have, please reopen and we will investigate further.
