### ISSUE TITLE
Update getting started script

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#48]
The getting started scripts should automatically generate random project names so that code can be copied and pasted

**Comment by kdaily** [comment]
A real word-based project name, or a prefix/suffix of timestamp or random text from the stdlib?

**Comment by kdaily** [comment]
Have an attempt, but getting javascript or html into Liquid tags and/or Pygments blocks is nigh impossible.

**Comment by kdaily** [comment]
Unfortunately it's extremely difficult to get javascript or raw HTML inside of Liquid tags and/or Pygments, so not sure how useful this is (since user would have to copy-paste twice - once for project name, once for code).

**Comment by kdaily** [comment]
#55 fixes this (not as gracefully as we would have liked).
