### ISSUE TITLE
Safari display funky

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#482]
The way docs render in Safari is not correct. 
![screen shot 2018-11-30 at 1 20 18 pm](https://user-images.githubusercontent.com/40647130/49315531-eb0a4c00-f4a2-11e8-99a8-dfc7f79fdff1.png)

@meredithslota I wanted to file a Jira, but I understand you are the expert to resolve this problem.

**Comment by meredithslota** [comment]
Ok, root cause of described issue is zoom level -- a higher zoom level was kicking it into "mobile view" even on laptop screens. HOWEVER, during testing we found that the tiles on https://docs.synapse.org/articles/ are not laid out correctly on Safari, so we'll use this issue to track that.

**Comment by meredithslota** [comment]
@kelshmo I did not take a screenshot and now despite my notes, I don't remember what this issue is about. Assigning to you to document how/why this isn't right and then I can try to fix. Apologies!

**Comment by kelshmo** [comment]
I can't reproduce it either! In fact, upon testing the tiles reformat beautifully when zooming in/out and modifying window size.
