### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseDocs#499]
I just merged PR #498 and received an email that the build is failing:

`The page build failed for the `master` branch with the following error:

The tag `tabs` on line 33 in `articles/annotation_and_query.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.`

However, I didn't touch that file in my PR - just made a small edit to a challenge doc. Any insight @kdaily @kelshmo?

**Comment by kdaily** [comment]
Common error, just go into Travis and trigger it to be rebuilt. One of these days we should figure out why, but I for the life of me have no idea!

**Comment by allaway** [comment]
That's weird - if I go here
<https://travis-ci.org/Sage-Bionetworks/synapseDocs>, it says it's now
passing, and there is no history of the failed build...

**Comment by kimyen** [comment]
The docs site is no longer built on Travis.
