### ISSUE TITLE
Move Python API docs to publish into new site

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#5]
The Python docs: http://python-docs.synapse.org should be posted to the main site.

**Comment by ychae** [comment]
To build to new site:

aws s3 sync _build/html/ s3://docs.synapse.org/python

**Comment by larssono** [comment]
@cbare:  Can you verify that you have the instructions and are set to deploy the code to docs.synapse.org/python the next time we releasea Python client.
