### ISSUE TITLE
annotations and query

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#50]
Add to annotation_and_query.md content beyond the query.

* What are anntoations
* How to assign annotations
* How to query on annotations (remember Python, R, command line and wiki widget)
* How to download based on queries (command line client)

**Comment by kdaily** [comment]
See https://gist.github.com/kdaily/50fe76f895a9747a68c9 for inspiration (or I can take this task)

**Comment by larssono** [comment]
Some minor issues with current status:
1. Examples for web-client should be under the same grouping as the code examples (see getting_started guide)
2. We need a very broad intro of motivation that introduces the uses of queries and annotations.
