### ISSUE TITLE
Installation instructions for Clients Needs to be more Prominent

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/synapseDocs#501]
This information is hard to find and is a critical "Getting Started" step. Links to this info should be displayed more prominently on the Docs front page or from the "Getting Started" page.

**Comment by kdaily** [comment]
@sieberts - @karawoo and I recently revamped the Getting Started page to be focused more on the web and not on the clients. Most of the users who get to this page need to know how to navigate the simple basics of Synapse. Most users do not 'get started' with the clients!

That being said, there is definitely a followup article that is critical to fill in exactly what you are asking for - where do users go after they have gotten started? And one place is to program with Synapse. I'll bump up this in priority and give it a pass, maybe with @kelshmo who does this a lot too!

**Comment by kdaily** [comment]
Indeed @sieberts! We have a meeting this Friday. I'll talk with @kelshmo.

FWIW there is an incomplete start at this here:

https://docs.synapse.org/articles/client_configuration.html

We've also tried to be less redundant - the best place to get started with the clients is on the individual language doc pages. The first order of business to making a new 'getting started with the clients' page is to get people to those pages ASAP!

**Comment by kelshmo** [comment]
@kimyen and I discussed the utility of that config page and the possibility of deprecating direct editing of a hidden file as it not at all user friendly. I think our current disconnect is that in re-vamping the Getting Started page and localizing code to the respective client pages, we are not providing enough context for new users (our one-liner at the bottom is [this page](https://docs.synapse.org/articles/getting_started.html) easily missed). I suggest we build out more instruction on the Getting Started page. To discuss more in our meeting Friday.

**Comment by kdaily** [comment]
:+1: !

And that it's not visible at all here: https://docs.synapse.org/articles/

And that the only place on any page that you can directly get to it is under "API docs" - the Python and R clients are not APIs!

![eeyore](https://media.giphy.com/media/Ennb4fZczzAS4/giphy.gif)

**Comment by kelshmo** [comment]
https://github.com/kelshmo/synapseDocs/blob/iss501/articles/getting_started_clients.md

@kdaily could you add some command line-specific commentary? 

@kimyen could you add some explanation for the python client?

**Comment by kdaily** [comment]
@sieberts how's it look?

https://docs.synapse.org/articles/getting_started_clients.html

If you approve go ahead and close this please!
