### ISSUE TITLE
Python docs search result descriptions rendering raw html

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseDocs#502]
The search results within the Python Documentation show raw HTML in the descriptions. Please see attached screenshot. 

![search_description_html](https://user-images.githubusercontent.com/12868382/51343251-da119c00-1a4a-11e9-9055-52baf4aae5cd.png)

**Comment by kimyen** [comment]
Thanks @ychae ! I can repro. I created a Synapse Python client issue to track the progress here: https://sagebionetworks.jira.com/browse/SYNPY-908

**Comment by ychae** [comment]
Thanks @kimyen!

**Comment by meredithslota** [comment]
https://sagebionetworks.jira.com/browse/SYNPY-908 is now closed, checking on the example in the ticket (https://python-docs.synapse.org/build/html/search.html?q=challenge&check_keywords=yes&area=default) still shows HTML leaking through. This is not yet fixed.

**Comment by kelshmo** [comment]
Closing as this issue is tracked in Jira.
