### ISSUE TITLE
Add documentation related to API key

### ISSUE THREAD

**Issue by kimyen** [Sage-Bionetworks/synapseDocs#508]
Including:
* What are the benefits of using API key vs. password? Why should one use API key?
* Where can users find their API key?

I will create client Jira tickets to add instructions on how to login with the R and Python client using API key.

**Comment by kimyen** [comment]
Python ticket: https://sagebionetworks.jira.com/browse/SYNPY-917
R ticket: https://sagebionetworks.jira.com/browse/SYNR-1383

**Comment by kdaily** [comment]
Note from Slack via @kimyen that an API key can be invalidated (even via the web) but a password could be changed by a nefarious user and lock the original user out of their account. Huge use case for security of scripts/apps/services using Synapse.

**Comment by kimyen** [comment]
The Python and R client portion of this ticket has been completed: 
* https://python-docs.synapse.org/build/html/Credentials.html
* https://r-docs.synapse.org/articles/manageSynapseCredentials.html

**Comment by kimyen** [comment]
Notes that after the information about API key available on synapseDocs, we need to link back to that page from the R and Py client docs.

**Comment by kdaily** [comment]
Discussed in today's docs meeting, a proposal (looks like @kimyen already did this for the R client, we should mirror this everywhere ~for Python too~!):

User docs for the clients at the high level should tell users how to log in with their `username` and `password`, potentially with `rememberMe=True`. Anytime a `.synapseConfig` file is mentioned, documentation should show that they need to use `username` and `apikey`, not `password`. Using and discussing `apikey` and `.synapseConfig` should be targeted to developers.

I will open a Jira to remove the password option from the default configuration file for the user, and to remove any documentation about putting the password in that file.

**Comment by kimyen** [comment]
This is done.
