### ISSUE TITLE
articles/table_queries.md

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#51]
1. Update table help page with information from the R and Python table vignettes.
2. Write intro to Tables.

**Comment by kdaily** [comment]
For `R` see this pending PR for the R client:

https://github.com/kdaily/rSynapseClient/blob/1798044d0217c63615b07370a555c00e67b72561/vignettes/tables.Rmd

**Comment by larssono** [comment]
Example walkthrough from Python is:  
http://docs.synapse.org/python/Table.html#module-synapseclient.table

**Comment by larssono** [comment]
@ychae we need to add the images for the web portion.
