### ISSUE TITLE
Some sections of sample code don't render on Views page

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseDocs#517]
The sample code in [Create a file view](https://github.com/Sage-Bionetworks/synapseDocs/blame/6c968b29a70e5fdc4d9a8f48ba21ea1343f8df13/articles/views.md#L24-L46) and [Update annotations in bulk](https://github.com/Sage-Bionetworks/synapseDocs/blame/6c968b29a70e5fdc4d9a8f48ba21ea1343f8df13/articles/views.md#L93-L112) is not showing up on the rendered site: 

<img width="1367" alt="screen shot 2019-02-15 at 3 06 33 pm" src="https://user-images.githubusercontent.com/4452678/52889097-532c0e00-3133-11e9-8df3-da58f9b00a37.png">

Possibly this is because these code sections have only one tab each? The sample code in the "Query a view" section, which has multiple tabs, looks fine.

**Comment by meredithslota** [comment]
Fixed in #518.
