### ISSUE TITLE
Add version to synapseDocs

### ISSUE THREAD

**Issue by kimyen** [Sage-Bionetworks/synapseDocs#522]
It can just be a json file locate at docs.synapse.org/version, where each build, Jenkins will automatically increases the version and push this to S3. So that when something doesn't look right, we can quickly check if the synapseDocs available at https://docs.synapse.org has been updated.

**Comment by kdaily** [comment]
We have one!

https://github.com/Sage-Bionetworks/synapseDocs/blob/master/package.json#L3

**Comment by kdaily** [comment]
This is what we use in Agora for the data version. It is a manual process now, but doesn't need to be.

https://github.com/Sage-Bionetworks/Agora/blob/develop/package.json#L4

**Comment by kimyen** [comment]
@kdaily how does `package.json` is generated? How does changing the version in this file impact the package?

**Comment by kimyen** [comment]
I added `jenkins_build.json` to the docs at https://docs.synapse.org/jenkins_build.json to track which commit has been built.
