### ISSUE TITLE
update synapsr client config

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/synapseDocs#529]
This page should be updated to include the Synapse client configuration for R https://docs.synapse.org/articles/client_configuration.html

**Comment by kimyen** [comment]
The config file is mentioned in this R documentation: https://r-docs.synapse.org/articles/manageSynapseCredentials.html
-- as a synapser user, I think this information is sufficient. Is there any other information we should expose in the config file beside Synapse credentials?

**Comment by xdoan** [comment]
I was hoping you could link that file in the client configuration page, since right now it says "Currently, this feature is not available in synapser (the Synapse R client)." when there is and someone on that page might not keep searching for the other page.

**Comment by kelshmo** [comment]
@xdoan Can you confirm the edits to the [config doc](https://docs.synapse.org/articles/client_configuration.html) meet your needs?
