### ISSUE TITLE
How do I get/find out about an apikey?

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#545]
Moved here from https://sagebionetworks.jira.com/browse/SYNR-1410

Reported by [~cindy.molitor]:
```
I was setting up my .synapseConfig file using this page: https://r-docs.synapse.org/articles/manageSynapseCredentials.html and it recommends using a Synapse apikey instead of a password.  How do I get/find out about an apikey?
```

Recommend adding instructions on how to generate the api key (via the web client) to this doc page.

**Comment by kimyen** [comment]
This is a duplicated of #508
