### ISSUE TITLE
Document synMove

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseDocs#549]
The section on [moving a file](https://docs.synapse.org/articles/files_and_versioning.html#moving-a-file) says:
> The Python and R clients do not have a specific move function, but can be used to modify the parentId property of the file/folder to move it.

I don't think this is accurate since `synMove()` exists. Do others agree that the code examples should show `synMove()` instead? If so I'll put together a PR.

**Comment by kelshmo** [comment]
@karawoo I agree that sentence should be changed - as for code examples, we want to keep as many code examples out of the docs and in the respective client documentation. It would be more appropriate to link to [`synMove()`](https://r-docs.synapse.org/reference/synMove.html) and [`syn.move`](https://python-docs.synapse.org/build/html/Client.html#synapseclient.Synapse.move)

**Comment by karawoo** [comment]
Sounds good, does that mean we should remove the existing code examples in this section then?

**Comment by kelshmo** [comment]
Yes, exactly. 

We are moving code out of the docs (slowly) so that code lives somewhere it is tested and is updated appropriately with new client versions.
