### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#556]
Update docs based on Aaron's corrections: 
replace this: 
Any human data shared in Synapse, with or without Conditions for Use, must be de-identified according to HIPAA Standards and all applicable privacy laws and regulations [see Contributing Data, above]. If you believe data made available in Synapse has been posted with inappropriate Conditions for Use contact the ACT at act@sagebase.org or click on the Report Issue flag (found at the center of the header). This will trigger an email to the ACT who will contact you for more details.

with this: 
Data shared in Synapse may have Conditions for Use that define restrictions on how it may be disclosed or what the data set may contain based on privacy laws or regulation [see Contributing Data, above]. If you believe the data made available in Synapse have been posted inconsistently with the associated Conditions for Use, use the Report Issue flag in the header of the relevant file, table or folder. Flagging the data in this way will alert the Access and Compliance Team who will contact you for more detail. You may also email the Access and Compliance Team at act@sagebase.org directly to report possible incidents.

Update docs based on Christine's input: 
Add sentence "Please be mindful when sharing information. Do not send data or metadata via email."

**Comment by kelshmo** [comment]
@kimyen @kdaily Ann Novakowski is reporting edits to the Governance docs to me via a word doc. She doens't have a github account(as non-programmers wouldn't!). Most likely, we will meet when I return from vaca end of July, but she may come to one of the docs meetings in the meantime to report her findings to you.

**Comment by kimyen** [comment]
That sounds great! I'm looking forward to working with her on docs. :)

**Comment by kelshmo** [comment]
Add Code of Conduct as new subpage. Make edits to Governance Overview per Ann's work. Ann is working on a larger revamp to the Governance documentation - likely combining all sections into 1 page.

**Comment by ankimno** [comment]
Update: Code of Conduct should not be a subpage. Please incorporate into the relevant section on the [Synapse Commons Governance Overview](https://drive.google.com/file/d/10lDh3aEc92DYWX37R___4kvb3IUDDkly/view?usp=sharing) doc.

**Comment by ankimno** [comment]
Incorporated Kelsey's feedback. Document can be found [here](https://drive.google.com/file/d/10lDh3aEc92DYWX37R___4kvb3IUDDkly/view?usp=sharing).

**Comment by kdaily** [comment]
@kelshmo let's bump the priority on this and get it out at our next meeting!

**Comment by kelshmo** [comment]
Edits are on my local repo. I'm blocked by our broken synapse build.

**Comment by kdaily** [comment]
![sad](https://media.giphy.com/media/M28rUlcjueKUE/giphy.gif)

**Comment by kdaily** [comment]
Closed by #585
