### ISSUE TITLE
Search bar is missing

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseDocs#562]
It looks like the site is not able to access google custom search for some reason:

<img width="1600" alt="Screen Shot 2019-06-07 at 11 33 16 AM" src="https://user-images.githubusercontent.com/4452678/59125813-44eb4300-8918-11e9-9972-cb6646622b3c.png">

**Comment by jay-hodgson** [comment]
@kimyen , this was also talked about in the #synapse slack channel.
My guess is that @ychae set this up in her Sage Google account, and maybe it's finally been cleaned up?  
May need to recreate (and restyle).  https://cse.google.com/cse/

**Comment by kdaily** [comment]
@meredithslota did something with this right before she left, but I don't recall exactly what. I thought she got a new search code/id thingy?

**Comment by jay-hodgson** [comment]
@kdaily : Right you are!  @meredithslota  [created a new CSE and added it to the header](https://github.com/Sage-Bionetworks/synapseDocs/commit/69b10f7fb79d0dcc136a76e8b239ef2570e34c0c#diff-822e9cf54ee310f9a7ebd0d16c9ae066), and [removed the old one](https://github.com/Sage-Bionetworks/synapseDocs/commit/77469f178215cfddd049a4edc638ae0177490184#diff-822e9cf54ee310f9a7ebd0d16c9ae066).

**Comment by jay-hodgson** [comment]
Should be fixed after next deployment.
https://github.com/Sage-Bionetworks/synapseDocs/pull/563
