### ISSUE TITLE
update external storage locations md5 instructions

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#564]
The example uses the string `"md5"` as the value for the MD5 of a file handle. This should be clarified that this needs to be a valid MD5 or the file will not be downloadable. This came up similarly in https://sagebionetworks.jira.com/browse/PLFM-5609.

**Comment by kimyen** [comment]
The user interaction should be:
* save an external file handle with incorrect md5
* receive a 4xx http error with message about the incorrect md5 format
* fix the md5 and try again

User should not have to go to the docs to figure out that they need to use correct md5 format for an md5 field. 
I'm closing this issue in favor of https://sagebionetworks.jira.com/browse/PLFM-5613
