### ISSUE TITLE
remove code tabs

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#567]
![Screenshot from 2019-06-17 13-50-59](https://user-images.githubusercontent.com/84993/59635855-0b2fee80-9107-11e9-8615-2381d1a1ed90.png)

**Comment by kimyen** [comment]
1. I think all docs to replace tab in https://docs.synapse.org/articles/annotation_and_query.html is already available in Python client and R client docs. We just need to remove code block and add links to the Python docs and R docs.

**Comment by kimyen** [comment]
2. Created Jira ticket: https://sagebionetworks.jira.com/browse/SYNPY-979

**Comment by kimyen** [comment]
3. Create Jira ticket: https://sagebionetworks.jira.com/browse/SYNPY-980

**Comment by kimyen** [comment]
4. Created Jira ticket: https://sagebionetworks.jira.com/browse/SYNPY-981

**Comment by kimyen** [comment]
5. Created Jira ticket: https://sagebionetworks.jira.com/browse/SYNPY-982

**Comment by kimyen** [comment]
6. Created: https://sagebionetworks.jira.com/browse/SYNPY-983

**Comment by kimyen** [comment]
7. We do not have much about Link to create a docs page in the client. I think high level document in synapse Docs is good enough here until we know what else to add.

**Comment by kimyen** [comment]
8. Created: https://sagebionetworks.jira.com/browse/SYNPY-983

**Comment by kimyen** [comment]
9. We have fully written document on Views on both R and Python client. We just need to replace the code block with links to the client docs:
* https://python-docs.synapse.org/build/html/Views.html
* https://r-docs.synapse.org/articles/views.html

**Comment by kimyen** [comment]
10. Created: https://sagebionetworks.jira.com/browse/SYNPY-985

**Comment by kdaily** [comment]
Work is ongoing in branch https://github.com/Sage-Bionetworks/synapseDocs/tree/change-tabs-to-fences.

**Comment by kimyen** [comment]
@kdaily , I also add this PR: https://github.com/Sage-Bionetworks/synapseDocs/pull/568 -- it restricted the heading level in table of content (toc).
