### ISSUE TITLE
Article not rendered correctly

### ISSUE THREAD

**Issue by marcomarasca** [Sage-Bionetworks/synapseDocs#570]
The following article https://docs.synapse.org/articles/accounts_certified_users_and_profile_validation.html is not rendered correctly (Reached from https://docs.synapse.org/articles/getting_started.html under the "Become a certified user" link).

**Comment by kimyen** [comment]
It rendered correctly now. You may want to clear the browser cache or open in in-cognitive browser to see the change today.
