### ISSUE TITLE
Docs information infrastructure 

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#578]
#546 delineates proposed topics

@lbradic User stories to address whether topic organization meets user needs:
1. New users. Docs will guide user to immediately start using Synapse and provide next steps for further exploration. Highlight available projects/research initiatives.
2. Existing users.  ~~They use the search bar in docs to find specific feature, function or technical limitation of the platform.~~ 1. They know how docs are structured, so they know where to go to find the right article. 2. They may use a search bar to look for novel features 
3. Exploratory. Users understand the basics of Synapse and want to see novel capabilities of Synapse, plus new features as they become available. Synapse In Practice guide is currently implemented to address synthesis of multiple features or more niche use cases.

**Comment by kelshmo** [comment]
@lbradic Example use cases for why an individual would arrive at the docs site and what they hope to accomplish: 

1. New users.
-  I've never used Synapse and I need to upload my data to a folder. I prefer to use Python, but I would like to understand the most efficient way to upload data.
- I'm thinking about putting data on Synapse but need to make sure the data will be disseminated in compliance of my NIH funding. 
2. Existing users. 
- I want to find all the RNASeq data across multiple projects. I need to know where and how to look for this data. 
- I want a step of my analysis workflow to be to programmatically download data. 
- I can't find what I'm looking for, how do I get help?
- How can Synapse help me keep track of file processing steps?
- Is there a best practice for how to structure data in Synapse?
- I want my data to be easily searchable by other users. 
3. Exploratory 
- What data is on Synapse? 
- Can Synapse help me distribute my data to collaborators? 
- Will Synapse make my bioinformatic processing pipeline easier?

**Comment by kdaily** [comment]
I'm a developer and want to use Synapse in my own tool.

**Comment by ychae** [comment]
Another one I'd add is:
2. Existing users: 

- How do I set-up and run a challenge?

**Comment by kdaily** [comment]
Gates Ki India onboarding presentation:

https://docs.google.com/presentation/d/1Gpgx9hL5_Ly1Pa6ZYoW3uftd9n17zMpxVI8ad23z2hM/edit

**Comment by kdaily** [comment]
@Dumindaaa is currently working on this and should have all of this information.
