### ISSUE TITLE
add to challenge setup instructions how to configure participation statistics

### ISSUE THREAD

**Issue by brucehoff** [Sage-Bionetworks/synapseDocs#583]
To collect participant statistics on a challenge, the procedure is to 'share' the relevant submission queues with the 'evaluationstatistics' service account:
https://www.synapse.org/#!Profile:3321925
giving the account 'Can Score' access permission to the chosen queue. After doing this the participation statistics will be displayed and updated once per day here:
https://www.synapse.org/#!Synapse:syn2504723/wiki/65150

A likely place to add these instructions is here:
https://docs.synapse.org/articles/challenge_administration.html

**Comment by kelshmo** [comment]
@brucehoff I'm not sure I understand. Can you open a PR and propose changes on the Challenge Guide page?

**Comment by brucehoff** [comment]
Yes!  Please review https://github.com/Sage-Bionetworks/synapseDocs/pull/647
