### ISSUE TITLE
Sentence about uploading multiple annotations is missing keyword

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/synapseDocs#592]
Sentence is: To add annotations on multiple files, please refer to our Synapse in Practice article “Managing Custom Metadata at Scale” for a tutorial on how to do this efficiently and effectively leveraging .

This sentence is missing a word at the end after "leveraging." The sentence is in the documentation twice.

Link: https://docs.synapse.org/articles/annotation_and_query.html

Does anyone know what word is supposed to be there? We can fix it.

**Comment by kdaily** [comment]
Welcome @Aryllen! Thanks for catching that. I might suggest we end both sentences at 'for a tutorial'. Please feel free to make that change - if you need some guidance on how to modify docs pages, feel free to follow up with me (we also have a docs meeting today, Monday)!
