### ISSUE TITLE
Remove permanent horizontal scrollbar

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/synapseDocs#599]
There is a style issue that makes the content of the page systematically wider than the width of the browser that may lead to an horizontal wobbling effect (see GIF below, observed on latest Chrome and Firefox).

![synapse_doc_horizontal_scroll](https://user-images.githubusercontent.com/3056480/65551195-2c5a6500-ded6-11e9-88f2-f2c5015d5529.gif)

**Comment by kdaily** [comment]
Thanks @tschaffter! A known issue that won't be addressed now, as it was inherited from the existing docs site (it has the same issue). I will leave it open but this will be addressed with the redesign effort, unless someone with CSS/HTML expertise can pinpoint the issue.

**Comment by jay-hodgson** [comment]
This is another easy fix.  The Bootstrap **row** class has negative margins.  This row is inside a **container**, which usually has a 20px padding to compensate, but right the element has a style with padding set to 0 0 0 0.
Change this to '0px 15px 0px 15px' and the horizontal scroll bar will go away.

<img width="1425" alt="Screen Shot 2020-03-26 at 10 34 53 AM" src="https://user-images.githubusercontent.com/1864447/77677879-8e5f5a00-6f4d-11ea-8928-79fa5b56a560.png">

**Comment by kelshmo** [comment]
Fixed in #763
