### ISSUE TITLE
Documentation of Table renderers

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/synapseDocs#620]
Synapse Tables, Fileviews, Leaderboards have renderers such as "userId, entity, datetime...." Is there documentation of this somewhere?

**Comment by kdaily** [comment]
Not to my knowledge!

**Comment by kdaily** [comment]
@thomasyu888 could you write a draft of this within two weeks?

**Comment by thomasyu888** [comment]
I think there actually is information about this here: https://docs.synapse.org/articles/tables.html#defining-a-schema.  That being said, there isn't information on leaderboard renderers, but there is a whole epic on updating evaluation queue queries to use the table query service....
