### ISSUE TITLE
change REST link on API docs page to rest-docs.synapse.org

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseDocs#630]
Xa is changing the deployment bucket for the REST docs to this, and it will be consistent with the rest of our `XXX-docs.synapse.org` sites.

**Comment by xschildw** [comment]
Note that the path is still needed: 'https://rest-docs.synapse.org/rest.

**Comment by kdaily** [comment]
@xschildw Thanks was just testing this!
