### ISSUE TITLE
Page build warning in my fork

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/synapseDocs#641]
I get an email with this content:

> The page build completed successfully, but returned the following warning for the `gh-pages` branch:
> 
> The CNAME `user-guides.synapse.org` is already taken. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken for more information.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.
>

**Comment by kdaily** [comment]
That's expected! The file `CNAME` file in this repository has that. If you fork and try to build based on the same CNAME, then you would get this warning. We chould add this to the contributing section though - but this method of 'testing' isn't recommended. You should use the documentation on how to build locally. If you are only making simple Markdown changes, then previewing in any Markdown editor should suffice as well. Thanks!

**Comment by thomasyu888** [comment]
I see.  I didn't try to build though.  The only thing I did was fetched upstream `gh-pages` and created my own `gh-pages` branch so it can always mimic that of upstream `gh-pages`.  Good to know.

**Comment by kdaily** [comment]
You inherit the settings on the repository as well, it seems. Which means GitHub pages is enabled on the `gh-pages` branch of your fork. Then, anything you commit to it will automatically trigger a build (it's a built in continuous integration and deployment system).

You can change that by disabling GitHub Pages on your fork in the main settings of the repository!
