### ISSUE TITLE
Unformatted examples in the Python synapseutils copy documentation

### ISSUE THREAD

**Issue by cw-dvr8** [Sage-Bionetworks/synapseDocs#662]
Some of the examples in the copy documentation here:

https://python-docs.synapse.org/build/html/synapseutils.html

have not been formatted such that they are easily readable.  For instance, the example for synapseutils.copy.copy is:

Examples:: import synapseutils import synapseclient syn = synapseclient.login() synapseutils.copy(syn, …)

This one also appears to be incomplete.

**Comment by kdaily** [comment]
Thanks for the report! Since this is documentation is in the Python client, this should be filed in the Synapse Python client codebase. I'm happy to do that, but can leave it for you to do as well, @cw-dvr8. Just let me know!

**Comment by cw-dvr8** [comment]
@kdaily When I tried to create the Jira ticket in the Synapse Python Client queue I got the following error message:

The default assignee does NOT have ASSIGNABLE permission OR Unassigned issues are turned off.

It apparently doesn't like the Assignee being "Automatic".  Is there anyone in particular I should assign this too?

**Comment by kdaily** [comment]
Bruce, thanks! Will talk to you offline about this issue.

**Comment by cw-dvr8** [comment]
The issue is https://sagebionetworks.jira.com/browse/SYNPY-1028 .
