### ISSUE TITLE
Can't go back one page to docs from Synapse

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#666]
If I click on the [Profile Page](https://docs.synapse.org/articles/user_profiles.html#managing-your-profile) link I am sent to Synapse and can not use the back button to return to the article I was reading.

**Comment by kelshmo** [comment]
@kdaily won't fix?

**Comment by kdaily** [comment]
I just tested and it seemed to work! Is it still broken for you?

**Comment by kelshmo** [comment]
Click on Projects under [Making and Managing Projects in Synapse](https://docs.synapse.org/articles/getting_started.html).

**Comment by kdaily** [comment]
😱 If you go to the main profile page it works, but any profile 'sub-page' it's broken. I suppose it can be a SWC Jira and then we could close it if that is a won't fix?

**Comment by kelshmo** [comment]
[SWC-5109](https://sagebionetworks.jira.com/browse/SWC-5109)
