### ISSUE TITLE
How to make "Challenge" tab appear in project

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/synapseDocs#667]
Does there exist a way to make the Challenge tab appear by using the web UI rather than the clunky client functions?

The docs (https://docs.synapse.org/articles/evaluation_queues.html) currently say:

> Please note that a Challenge tab will not appear on your project until you have created a challenge (Tools > Run Challenge).

But that interface doesn't exist anymore.

**Comment by kdaily** [comment]
It should read 'Project Settings > Run Challenge'. Thanks for filing!

**Comment by philerooski** [comment]
I don't see it there, either

![image](https://user-images.githubusercontent.com/2773709/70098200-24a6f300-15e0-11ea-9abb-f2282c82017d.png)

**Comment by kdaily** [comment]
D'oh! Correction: you need to be in 'alpha mode' and then use the 'Project Settings' menu.

**Comment by thomasyu888** [comment]
Its either that or you have to append `/challenge` to a project URL (e.g. `https://www.synapse.org/#!Synapse:projectid/challenge/`)

**Comment by thomasyu888** [comment]
The instructions tell the user to append `/challenge` to the project url
