### ISSUE TITLE
Multi-tag in yaml headers

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/synapseDocs#677]
Multiple articles should be in different subheadings on the main Articles page. Look into whether it's possible to multi-tag an article in the yaml header that will allow this to happen. This may need a jekyll plugin.

**Comment by Aryllen** [comment]
Still trying to figure this out, but slow going since I'm not familiar with Jekyll. This post might be helpful: https://stackoverflow.com/questions/1408824/an-easy-way-to-support-tags-in-a-jekyll-blog/21002505#21002505

**Comment by kdaily** [comment]
I think I figured this out as part of #678!

**Comment by Aryllen** [comment]
Closing since this will be fixed in #678.
