### ISSUE TITLE
Category for OAuth

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#681]
Where can [using the OAuth client](https://github.com/Sage-Bionetworks/synapseDocs/blob/gh-pages/articles/using_synapse_as_an_oauth_server.md) live?

**Comment by kelshmo** [comment]
Add to Administration and Settings

**Comment by Dumindaaa** [comment]
Again - I really jumped the gun with this one. I think really should go as a standalone article within API. Since it's not really about a general user setting, and is predominantly around using Programmatic Clients
