### ISSUE TITLE
Is this page obsolete?

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#682]
Does [this page](https://github.com/Sage-Bionetworks/synapseDocs/blob/gh-pages/articles/synapse_in_practice.md) need to continue to exist? I believe it indexed the In-Practice sub-page in our previous design iteration.

**Comment by kdaily** [comment]
The current thought is that we want to incorporate 'in practice' docs into one of the other sections, but highlight them as in practice docs. I think having them indexed on the full article index page is sufficient, so would agree that this particular page is redundant. I'll remove it.

**Comment by kdaily** [comment]
fixed by https://github.com/kdaily/synapseDocs/commit/ab9d8829454777acc2863a8dd2c91d172a3dfdfb
