### ISSUE TITLE
FAQ location

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/synapseDocs#683]
The latest model for the new docs site does not have a category shown for the [FAQ](https://github.com/Sage-Bionetworks/synapseDocs/blob/gh-pages/articles/faq.md). Should this be a category or will this be accessed somewhere else?

**Comment by Dumindaaa** [comment]
The FAQ should be accessed from the Primary Navigation and from the Docs Homepage, as a link. So it doesn't need exist within the main 'Categories' page (i.e. with the boxes), and definitely does not need to be on the 'list' page. 

If/when we improve it, it could potentially go on the main Categories (Boxes) page, perhaps under "Before you begin", but we can consider that later
