### ISSUE TITLE
forms article category

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/synapseDocs#684]
What category (or categories) should the [forms.md](https://github.com/Sage-Bionetworks/synapseDocs/blob/gh-pages/articles/forms.md) article be in?

**Comment by Dumindaaa** [comment]
Collaboration and Communication - since the feature is ultimately a collaborative one 

Note: it could also potentially fit into 'data management', since it is about getting data into Synapse, however we aren't doing this documentation in a chronological way (For now...)

**Comment by kdaily** [comment]
Would also say that it went into 'data management'...

**Comment by kelshmo** [comment]
Category needs to be updated to appear on the site.
