### ISSUE TITLE
links article category

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/synapseDocs#687]
What category (or categories) should the [links.md](https://github.com/Sage-Bionetworks/synapseDocs/blob/gh-pages/articles/links.md) article be in?

**Comment by Dumindaaa** [comment]
It should be in "Collaboration and Communication" 

One question I have as a reader of this article is: In what context(s) would a user want to create a link?
Once i have a link, how do I use it?

**Comment by Dumindaaa** [comment]
Note: this is a good example of a feature that I believe could have a bunch of value for the purposes of collaborations, and we could consider very briefly laying our the purposes and next steps of using this feature within this article.

**Comment by kdaily** [comment]
I might argue that this goes into 'managing data in synapse'. One often creates links to include a data file in a folder where it doesn't actually live to make it easier to download it with other things. It's currently mostly used administratively.

**Comment by kelshmo** [comment]
This article is not being surfaced on the site as the how-to category no longer exists.

**Comment by kelshmo** [comment]
Managing Data in Synapse - category

**Comment by Aryllen** [comment]
Fixed with #768
