### ISSUE TITLE
managing teams article category

### ISSUE THREAD

**Issue by Aryllen** [Sage-Bionetworks/synapseDocs#688]
What category (or categories) should [managing_teams_for_groups_and_projects.md](https://github.com/Sage-Bionetworks/synapseDocs/blob/gh-pages/articles/managing_teams_for_groups_and_projects.md) be in? It's currently in `in-practice`, but it seems like this should have multiple categories.

**Comment by Dumindaaa** [comment]
This should also be in "Collaboration and Communication", and it should directly follow on from teams

If going in multiple categories, then it should probably also go into "Governance"

**Comment by kdaily** [comment]
Fixed with commit ed55810e
