### ISSUE TITLE
Increase padding between categories on the Articles Index Page

### ISSUE THREAD

**Issue by Dumindaaa** [Sage-Bionetworks/synapseDocs#692]
Currently, there is no padding between sections on the articles index page, so when a user clicks on a specific category from the Articles Homepage (http://kdaily.github.io/synapseDocs/articles/), once they arrive on the list page, they still have the problem of not really being able to see where their category is.

Placing clear padding between the sections will improve this:

![image](https://user-images.githubusercontent.com/50338625/74872481-1f6d6080-5312-11ea-9390-15bf35726209.png)

**Comment by kdaily** [comment]
Temporarily fixed by https://github.com/kdaily/synapseDocs/commit/ea7a7b4f5d6c2d324bfe1644f8a645b8d8fea249

This should get web developer attention.
