### ISSUE TITLE
Rest docs moved to main site

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#7]
The rest docs (rest.synapse.org) need to be moved to main doc site.

**Comment by ychae** [comment]
Using wget to move site:
wget -r -p -k --level=1 -nH -H http://rest.synapse.org

basic syntax: wget [option]… [URL]…
wget docs: https://www.gnu.org/software/wget/manual/wget.html

**Comment by xschildw** [comment]
Need to create a IAM account in dev with rights to read from release docs bucket, and give that
account the right to write in the 'official' docs bucket in prod. Then see if links are OK after sync.

**Comment by larssono** [comment]
@xschildw: is this currently being done during the Synapse release cycle?  If so can you close this issue and add a link/redirect from rest.synapse.org to docs.synapse.org/rest

**Comment by xschildw** [comment]
I think it's an S3 redirect rule from docs.synapse.org to rest.synapse.org.

**Comment by xschildw** [comment]
It's a rules redirect, I fixed the key to '/articles/api_docs.html'
to match the link on the page. Btw why can't we just change
the link to point to 'http://rest.synapse.org'?

**Comment by larssono** [comment]
Primarily to make all docs searchable in one domain. Also make it easy for someone to find all docs in one place without having to remember URLs. 
--
Sent from myMail app for Android Friday, 03 June 2016, 10:25AM -07:00 from Xavier Schildwachter  notifications@github.com :

**Comment by larssono** [comment]
@xschildw Did you create a redirect from http://docs.synapse.org/articles/api_docs.html to http://hud.rel.rest.doc.sagebase.org.s3-website-us-east-1.amazonaws.com/?  If so the redirect is in the wrong direction and not specific enough. http://docs.synapse.org/articles/api_docs.html should contain a html page that @ychae created with links to all of the API docs (R, Python, Command line and REST).
 The content of rest.synapse.org should be stored in docs.synapse.org/rest/ and preferably we would deprecate rest.synapse.org such that it redirects to docs.synapse.org/rest/

**Comment by xschildw** [comment]
I removed the redirect and now see the landing page @ychae created. Currently syncing the docs
from rest.synapse.org, I'll look into moving the generation to the new spot.
