### ISSUE TITLE
Remove "getting started" from articles index page

### ISSUE THREAD

**Issue by Dumindaaa** [Sage-Bionetworks/synapseDocs#701]
Since a link to 'getting started' article is contained within the 'onboarding' section of the articles list page, and also, since the button on the articles category page also takes the user to the article itself, it doesn't need its own section on the articles list page

**Comment by kelshmo** [comment]
- [x] remove get-started category from article
- [x] remove getting started section from index page using logic

**Comment by kelshmo** [comment]
Will also impact #704.
