### ISSUE TITLE
Change order of article categories on the articles index page

### ISSUE THREAD

**Issue by Dumindaaa** [Sage-Bionetworks/synapseDocs#702]
The order of categories should follow the same order as on the category page, which when correct, should be:

Onboarding
governance
projects
managing data
uploads and annotations
collaboration and communication
search and discovery
administration and settings
API Clients

Reproducible research
Challenges
Synapse in Practice

**Comment by kelshmo** [comment]
Fixed by https://github.com/kdaily/synapseDocs/pull/12
