### ISSUE TITLE
Change order of categories on Articles category page

### ISSUE THREAD

**Issue by Dumindaaa** [Sage-Bionetworks/synapseDocs#703]
The order of categories should be

**Before you start**
Getting started
Onboarding
governance

**Core components**
projects
managing data
uploads and annotations
collaboration and communication
search and discovery
administration and settings
API Clients

**Additional components**
Reproducible research
Challenges
Synapse in Practice

**Comment by kelshmo** [comment]
Fixed by https://github.com/kdaily/synapseDocs/pull/12
