### ISSUE TITLE
change order of articles on the index page, to be in the order that a user might interact with features

### ISSUE THREAD

**Issue by Dumindaaa** [Sage-Bionetworks/synapseDocs#707]
We need to finalize an order for articles on the list page. For example, "Getting Started with Synapse" should be the first article on the page (under onboarding), "Governance Overview" should be the first article under Governance.

Note that many of these may already be correct, but it is worth reviewing .

**Comment by kelshmo** [comment]
More complicated than anticipated - we need to explore further why order is not preserved when multiple categories are in the `category` article array.

**Comment by Dumindaaa** [comment]
That is ok, we can look into it further

**Comment by kelshmo** [comment]
Temporary workaround: display articles under a single category so explicit order is preserved.

**Comment by kelshmo** [comment]
Getting Started with API clients needs to be reordered, for example.
