### ISSUE TITLE
Url to install python client returns 404

### ISSUE THREAD

**Issue by tthyer** [Sage-Bionetworks/synapseDocs#712]
On the command line client page (https://python-docs.synapse.org/build/html/CommandLineClient.html), the link for "installation of the Synapse Python Client" produces a 404.

I reached that page by going to synapse.org and clicking on "command line client" under Help > Programmatic Clients.

**Comment by kdaily** [comment]
Thanks @tthyer! The link should be https://python-docs.synapse.org/build/html/index.html#installation.

**Comment by kdaily** [comment]
I migrated this to Jira, as it's part of the automated build and deploy process of the Python client itself.

https://sagebionetworks.jira.com/browse/SYNPY-1044
