### ISSUE TITLE
Update user guide layout.

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#72]
1. In addition to just lising the title can we add a brief synopsis in the user guide listing.  Perhaps we can use: http://www.seanbuscay.com/blog/jekyll-teaser-pager-and-read-more/
2. http://docs.synapse.org/articles/ currently contains a list which has a link "User Guide" that leads to http://docs.synapse.org/articles/.html

**Comment by larssono** [comment]
Can the excerpts not be part of the rendered article?

**Comment by ychae** [comment]
Excerpts are now part of the yaml header and aren't rendered in the main page of the article.
