### ISSUE TITLE
Broken links on user accounts page

### ISSUE THREAD

**Issue by leammartin** [Sage-Bionetworks/synapseDocs#731]
Both links under the "See Also" section at the bottom of the User Accounts page are broken. 

Page: https://user-guides.synapse.org/articles/user_profiles.html 
Broken Link Names: "Accounts, Certification and Profile Validation", "Discussion"

**Comment by kdaily** [comment]
@leammartin I verified this is fixed, but please also check and let me know if you see a reocurrence.

**Comment by leammartin** [comment]
Just tried it and it works now :) thanks!!
