### ISSUE TITLE
Port issues to Jira

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#733]
Move issue tracking to [Jira](https://sagebionetworks.jira.com/secure/RapidBoard.jspa?projectKey=DOCS&rapidView=100).

**Comment by thomasyu888** [comment]
Are we thinking of doing something like this https://github.com/mongodb/mongo/wiki/Submit-Bug-Reports? I have also seen projects that have automatically create a Jira ticket based on a github issue (can't currently think of any) but this would allow for external users of our platform to potentially open tickets which could be tracked internally.

Personally, I think GitHub allows for external users an opportunity to contribute, and documentation is the best entry point for any open source project. I also think that the linking of github issues to pull requests is incredibly helpful.

**Comment by kelshmo** [comment]
Summarizing from a slack conversation - we are not going to devote the resources to this transition right now. 
- boardgenius not appropriate due to the ad-centric business model
- Zapier not appropriate because it is not a sync, issues need to be closed/transitioned in both places (deemed not appropriate by IT in another Sage project)
- free version of Jira to GitHub syncing is time consuming to set-up (probably needs an engineer and Jira admin a week of work to set-up)
