### ISSUE TITLE
Custom bucket storage location - provide further clarity

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/synapseDocs#756]
An external user provided documentation feedback per [PLFM-6000](https://sagebionetworks.jira.com/browse/PLFM-6000).

To summarize:

- Files added directly to the external bucket were not seen on Synapse. @nickgros can you comment on this - is this expected behavior?

- Recommended to include a short specification describing where the owner.txt file with read-write permissions should be uploaded. If uploading files to a folder within a bucket via Synapse, the owner.txt file must be in the folder itself.

**Comment by nickgros** [comment]
Point 1: the observed behavior is expected, I added a note clarifying that unless you upload through Synapse, you won't see the file. I also reference the section that describes adding files in a bucket to Synapse, which would allow a user to accomplish the desired behavior.

Point 2: I tried to clarify this where we introduce owner.txt in the Google Cloud section. I also more clearly demonstrated "base keys" (i.e. the subfolder name) in the programmatic examples

PR: https://github.com/Sage-Bionetworks/synapseDocs/pull/771
