### ISSUE TITLE
Docker image push

### ISSUE THREAD

**Issue by hellorp1990** [Sage-Bionetworks/synapseDocs#786]
Hi,
<img width="356" alt="Screen Shot 2020-06-15 at 8 08 49 AM" src="https://user-images.githubusercontent.com/19805255/84655982-ef108a00-aedf-11ea-87af-27aeba867c48.png">
 I am unable to push my docker image to the synapse docker registry. 
It is saying "denied: requested access to the resource is denied".  Please check the screenshot.
Docker push command:
docker push docker.synapse.org/synxxxxxxxx/model:v1

Can anyone please tell me what should I do here? I also have finished the certification quiz.

Rahul

**Comment by kelshmo** [comment]
Issue addressed here: https://www.synapse.org/#!SynapseForum:threadId=7164
