### ISSUE TITLE
article on versions

### ISSUE THREAD

**Issue by kkdang** [Sage-Bionetworks/synapseDocs#84]
I suggest we need a page on entity versioning -- this is NOT well adopted by many communities and leads to lots of confusion for users regarding what files to use.

**Comment by kdaily** [comment]
Agreed. Even for those who do use it, it can be confusing, as the default params for the programmatic clients differ from the web (forceVersion).

**Comment by larssono** [comment]
Perfect. The web also just added default versioning with uploads of files with the same name.

**Comment by kdaily** [comment]
We should cover:

1. forceVersion
1. what happens when changing annotations
1. out of date provenance
1. what should be best practice (`forceVersion=False` ALWAYS unless you know what you're doing)
1. R/python/web client differences in defaults and implementation (esp with storing annotations and the effect on file version)

**Comment by kkdang** [comment]
Agreed.
Assume what you mean in #3 is that provenance is associate with versions,
so isn't propagated when updating an entity to a new version.

Of course ideally there wouldn't be any differences in defaults across the
clients ...

**Comment by kdaily** [comment]
Yup - and that many 'broken' provenance graphs aren't really so, they're
what happens when people don't realize about `forceVersion` and make
changes to things other than file content (e.g. annotations).

**Comment by kdaily** [comment]
I could not find for the life of me any existing docs related to this (not in tutorial, current getting started, or either of the client-specific guides, and not really even in the auto-generated docs) - anyone have anything of their own (maybe @apratap, @brian-bot)?

**Comment by larssono** [comment]
I just have slides but nothing relevant to the doc site.

**Comment by apratap** [comment]
static picture and no text

**Comment by kdaily** [comment]
OSF just sent me an email about versioning help:

http://help.osf.io/m/files/l/524182-file-revisions-and-versions

**Comment by kkdang** [comment]
wow that looks a lot like synapse versioning

**Comment by kdaily** [comment]
Follow along at https://github.com/Sage-Bionetworks/synapseDocs/blob/articleOnVersioning/articles/versioning.md.

**Comment by kdaily** [comment]
Needs:

- [ ] `forceVersion=False`. Done.
- [ ] - what happens when changing annotations
- [ ] - out of date provenance
- [ ] - R/python/web client differences in defaults and implementation (esp with storing annotations and the effect on file version)

**Comment by ychae** [comment]
Note: file changes always cause a version update, metadata changes (such as annotations, provenance, etc) are optional (forceVersion = F)
Clients the default is forceVersion = T

**Comment by kdaily** [comment]
Is this finished? The one issue I have is with the name of the article (versioning) when it's really about files. This might be confusing to users. It will probably be a PITA to find all the places where it's linked to...

**Comment by kdaily** [comment]
I take that back. The section on uploading files should NOT be a sub-section of versioning. You don't necessarily need to understand what versions are to upload a file.

**Comment by kdaily** [comment]
See #225

**Comment by larssono** [comment]
The statement: 

> (e.g., the md5sum of the file is identical to the most recent version)

is actually wrong and should be removed.

**Comment by larssono** [comment]
Section "Uploading a New Version of a File"  should also indicate that you can update a file by just changing the file.path variable to point to a new local file.

**Comment by kdaily** [comment]
done, can address other issues separately.
