### ISSUE TITLE
Update links and code examples in Provenance

### ISSUE THREAD

**Issue by larssono** [Sage-Bionetworks/synapseDocs#85]
The links to the provenance article point to the deprecated sites r-docs, python-docs these are now under docs.synapse.org/python docs.synapse.org/r.

Also, can the code examples be combined into tabs as in the getting_started guide.

**Comment by ychae** [comment]
Updated links and code format but needs additional code examples

**Comment by larssono** [comment]
Remove links to synapse wiki's

**Comment by xschildw** [comment]
The layout does not look, 'Using command line...'. See attached.
![docs_provenance](https://cloud.githubusercontent.com/assets/1766159/16849099/cadeb5a8-49ad-11e6-90c1-0da2eee93c30.png)

**Comment by larssono** [comment]
Web content not in code tabs.  Also some of the web examples are missing.
